# data

In [6]:
# 서울시 평생교육기관 (유형별구별) 통계 (2012~2018)

import pandas as pd
edu_2012 = pd.read_csv('./서울시 평생교육기관 (유형별구별) 통계 (2012~2018)/서울시 평생교육기관 (유형별구별) 통계_2012.txt', sep='\t')
edu_2012 = edu_2012.iloc[:,[0,1,11,13]]
edu_2012 = edu_2012.rename(columns=edu_2012.iloc[0])
edu_2012 = edu_2012.drop([0,1])
edu_2012 = edu_2012.reset_index(drop=True)

import pandas as pd
edu_2013 = pd.read_csv('./서울시 평생교육기관 (유형별구별) 통계 (2012~2018)/서울시 평생교육기관 (유형별구별) 통계_2013.txt', sep='\t')
edu_2013 = edu_2013.iloc[:,[0,1,11,13]]
edu_2013 = edu_2013.rename(columns=edu_2013.iloc[0])
edu_2013 = edu_2013.drop([0,1])
edu_2013 = edu_2013.reset_index(drop=True)

import pandas as pd
edu_2014 = pd.read_csv('./서울시 평생교육기관 (유형별구별) 통계 (2012~2018)/서울시 평생교육기관 (유형별구별) 통계_2014.txt', sep='\t')
edu_2014 = edu_2014.iloc[:,[0,1,11,13]]
edu_2014 = edu_2014.rename(columns=edu_2014.iloc[0])
edu_2014 = edu_2014.drop([0,1])
edu_2014 = edu_2014.reset_index(drop=True)

import pandas as pd
edu_2015 = pd.read_csv('./서울시 평생교육기관 (유형별구별) 통계 (2012~2018)/서울시 평생교육기관 (유형별구별) 통계_2015.txt', sep='\t')
edu_2015 = edu_2015.iloc[:,[0,1,11,13]]
edu_2015 = edu_2015.rename(columns=edu_2015.iloc[0])
edu_2015 = edu_2015.drop([0,1])
edu_2015 = edu_2015.reset_index(drop=True)

import pandas as pd
edu_2016 = pd.read_csv('./서울시 평생교육기관 (유형별구별) 통계 (2012~2018)/서울시 평생교육기관 (유형별구별) 통계_2016.txt', sep='\t')
edu_2016 = edu_2016.iloc[:,[0,1,11,13]]
edu_2016 = edu_2016.rename(columns=edu_2016.iloc[0])
edu_2016 = edu_2016.drop([0,1])
edu_2016 = edu_2016.reset_index(drop=True)

import pandas as pd
edu_2017 = pd.read_csv('./서울시 평생교육기관 (유형별구별) 통계 (2012~2018)/서울시 평생교육기관 (유형별구별) 통계_2017.txt', sep='\t')
edu_2017 = edu_2017.iloc[:,[0,1,11,13]]
edu_2017 = edu_2017.rename(columns=edu_2017.iloc[0])
edu_2017 = edu_2017.drop([0,1])
edu_2017 = edu_2017.reset_index(drop=True)

import pandas as pd
edu_2018 = pd.read_csv('./서울시 평생교육기관 (유형별구별) 통계 (2012~2018)/서울시 평생교육기관 (유형별구별) 통계_2018.txt', sep='\t')
edu_2018 = edu_2018.iloc[:,[0,1,11,13]]
edu_2018 = edu_2018.rename(columns=edu_2018.iloc[0])
edu_2018 = edu_2018.drop([0,1])
edu_2018 = edu_2018.reset_index(drop=True)

edu_library = pd.concat([edu_2012, edu_2013, edu_2014, edu_2015, edu_2016, edu_2017, edu_2018], axis=0)
edu_library = edu_library.reset_index(drop=True)
edu_library

       기간  자치구 평생학습관 도서관
0    2012  종로구     3   1
1    2012   중구     1   1
2    2012  용산구     2   2
3    2012  성동구     1   4
4    2012  광진구     2   4
..    ...  ...   ...  ..
170  2018  관악구     3   4
171  2018  서초구     3   4
172  2018  강남구     5  10
173  2018  송파구     2  12
174  2018  강동구     3   7

[175 rows x 4 columns]

In [7]:
# 서울시 신고·등록 체육시설 통계 (2010~2019)

import pandas as pd
exercise = pd.read_csv('서울시 신고·등록 체육시설 통계 (2010~2019).txt', sep='\t')
exercise = exercise.iloc[:,[0,1,10,14]]
exercise = exercise.drop(exercise.index[[0,1]], axis=0)
exercise = exercise.rename(columns={'신고체육시설.6':'체육도장_시설수','신고체육시설.10':'체육단련장_시설수'})
mask = exercise['자치구'].isin(['서울시'])
exercise = exercise[~mask].reset_index(drop=True)
exercise

       기간  자치구 체육도장_시설수 체육단련장_시설수
0    2010  종로구       17        45
1    2010   중구       23        63
2    2010  용산구       41        29
3    2010  성동구       77        40
4    2010  광진구       94        83
..    ...  ...      ...       ...
245  2019  관악구      103        90
246  2019  서초구      114       196
247  2019  강남구       59       467
248  2019  송파구      149       191
249  2019  강동구       55       114

[250 rows x 4 columns]

# edu_library

In [78]:
edu_library.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175 entries, 0 to 174
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   기간      175 non-null    object
 1   자치구     175 non-null    object
 2   평생학습관   175 non-null    object
 3   도서관     175 non-null    object
dtypes: object(4)
memory usage: 5.6+ KB

In [79]:
edu_library.columns

Index(['기간', '자치구', '평생학습관', '도서관'], dtype='object')

In [80]:
edu_library.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175 entries, 0 to 174
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   기간      175 non-null    object
 1   자치구     175 non-null    object
 2   평생학습관   175 non-null    object
 3   도서관     175 non-null    object
dtypes: object(4)
memory usage: 5.6+ KB

In [81]:
edu_library = edu_library.astype({'평생학습관':int, '도서관':int})
# ValueError: invalid literal for int() with base 10: '-'

ValueError: invalid literal for int() with base 10: '-'

In [82]:
edu_library[edu_library['도서관'].isin(['-'])]

       기간   자치구 평생학습관 도서관
5    2012  동대문구     2   -
14   2012   양천구     2   -
20   2012   관악구     2   -
21   2012   서초구     2   -
24   2012   강동구     3   -
39   2013   양천구     2   -
46   2013   서초구     2   -
64   2014   양천구     2   -
116  2016   구로구     4   -
167  2018   금천구     3   -

In [83]:
edu_library[edu_library['자치구'] == '동대문구']

       기간   자치구 평생학습관 도서관
5    2012  동대문구     2   -
30   2013  동대문구     2   3
55   2014  동대문구     2   4
80   2015  동대문구     2   5
105  2016  동대문구     2  12
130  2017  동대문구     2  24
155  2018  동대문구     2   3

In [84]:
edu_library[edu_library['자치구'] == '양천구']

       기간  자치구 평생학습관 도서관
14   2012  양천구     2   -
39   2013  양천구     2   -
64   2014  양천구     2   -
89   2015  양천구     2   4
114  2016  양천구     3  24
139  2017  양천구     3  10
164  2018  양천구     3   5

In [85]:
edu_library[edu_library['자치구'] == '관악구']

       기간  자치구 평생학습관 도서관
20   2012  관악구     2   -
45   2013  관악구     2  10
70   2014  관악구     2  17
95   2015  관악구     2  23
120  2016  관악구     1  32
145  2017  관악구     2  37
170  2018  관악구     3   4

In [86]:
edu_library[edu_library['자치구'] == '금천구']
# 공공 도서관?

       기간  자치구 평생학습관 도서관
17   2012  금천구     2   4
42   2013  금천구     2   4
67   2014  금천구     2   5
92   2015  금천구     2   4
117  2016  금천구     2   4
142  2017  금천구     2   4
167  2018  금천구     3   -

In [ ]:
edu_library_gu = edu_library.groupby('자치구')
edu_library_gu

In [ ]:
edu_library_gu.sum()

In [70]:
import pandas as pd
print("pandas version: ", pd.__version__)
pd.set_option('display.max_row', 500)
pd.set_option('display.max_columns', 100)

pandas version:  1.0.1

In [ ]:
edu_library

# exercise

In [46]:
exercise.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   기간         250 non-null    object
 1   자치구        250 non-null    object
 2   체육도장_시설수   250 non-null    object
 3   체육단련장_시설수  250 non-null    object
dtypes: object(4)
memory usage: 7.9+ KB

In [2]:
exercise[exercise['체육단련장_시설수'].isin(['-'])]

       기간  자치구 체육도장_시설수 체육단련장_시설수
188  2017  마포구       15         -

In [8]:
exercise['체육단련장_시설수'] = exercise['체육단련장_시설수'].replace('-', '98')
exercise

       기간  자치구 체육도장_시설수 체육단련장_시설수
0    2010  종로구       17        45
1    2010   중구       23        63
2    2010  용산구       41        29
3    2010  성동구       77        40
4    2010  광진구       94        83
..    ...  ...      ...       ...
245  2019  관악구      103        90
246  2019  서초구      114       196
247  2019  강남구       59       467
248  2019  송파구      149       191
249  2019  강동구       55       114

[250 rows x 4 columns]

In [48]:
exercise[exercise['체육단련장_시설수'].isin(['-'])]

Empty DataFrame
Columns: [기간, 자치구, 체육도장_시설수, 체육단련장_시설수]
Index: []

In [49]:
exercise = exercise.astype({'체육도장_시설수':int, '체육단련장_시설수':int})
# ValueError: invalid literal for int() with base 10: '-'

exercise.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   기간         250 non-null    object
 1   자치구        250 non-null    object
 2   체육도장_시설수   250 non-null    int32
 3   체육단련장_시설수  250 non-null    int32
dtypes: int32(2), object(2)
memory usage: 6.0+ KB

In [6]:
exercise['체육도장_시설수'].unique()

array(['17', '23', '41', '77', '94', '99', '107', '93', '83', '137', '98',
       '73', '160', '150', '62', '69', '71', '126', '97', '144', '128',
       '21', '26', '39', '80', '100', '106', '92', '88', '130', '103',
       '68', '133', '151', '74', '108', '131', '148', '19', '27', '37',
       '85', '96', '95', '79', '104', '81', '145', '91', '67', '109',
       '121', '161', '135', '22', '36', '112', '156', '75', '113', '149',
       '132', '180', '89', '72', '116', '76', '110', '120', '157', '101',
       '65', '136', '169', '147', '25', '34', '51', '153', '82', '159',
       '87', '140', '142', '105', '154', '66', '119', '141', '8', '30',
       '48', '115', '15', '163', '117', '90', '102', '162', '152', '24',
       '84', '50', '45', '60', '78', '114', '164', '61', '118', '155',
       '31', '55', '64', '127', '134', '173', '59'], dtype=object)

In [7]:
exercise['체육단련장_시설수'].unique()

array(['45', '63', '29', '40', '83', '62', '48', '46', '41', '42', '71',
       '37', '69', '73', '53', '38', '82', '49', '78', '163', '104', '64',
       '32', '39', '86', '60', '43', '67', '79', '75', '58', '47', '85',
       '84', '234', '114', '66', '36', '61', '44', '77', '80', '87', '70',
       '92', '221', '126', '89', '50', '68', '91', '54', '88', '99',
       '240', '140', '95', '52', '93', '59', '57', '121', '150', '97',
       '72', '100', '51', '65', '133', '301', '139', '56', '101', '55',
       '109', '149', '340', '110', '74', '106', '-', '117', '115', '169',
       '374', '161', '108', '90', '119', '192', '398', '173', '103', '94',
       '120', '105', '157', '125', '196', '467', '191'], dtype=object)

In [12]:
exercise[exercise['체육단련장_시설수'].isin(['-'])]

       기간  자치구 체육도장_시설수 체육단련장_시설수
188  2017  마포구       15         -

In [14]:
exercise_mapo = exercise[exercise['자치구'] == '마포구']
exercise_mapo

       기간  자치구 체육도장_시설수 체육단련장_시설수
13   2010  마포구       94        69
38   2011  마포구      100        67
63   2012  마포구       81        79
88   2013  마포구       75        71
113  2014  마포구       80        71
138  2015  마포구       82        82
163  2016  마포구       81        88
188  2017  마포구       15         -
213  2018  마포구       94       108
238  2019  마포구       99       120

In [19]:
exercise_mapo[exercise_mapo['기간']!='2017']

       기간  자치구 체육도장_시설수 체육단련장_시설수
13   2010  마포구       94        69
38   2011  마포구      100        67
63   2012  마포구       81        79
88   2013  마포구       75        71
113  2014  마포구       80        71
138  2015  마포구       82        82
163  2016  마포구       81        88
213  2018  마포구       94       108
238  2019  마포구       99       120

In [26]:
aa = exercise_mapo[exercise_mapo['기간']!='2017']

aa = aa.astype({'체육단련장_시설수':int})
aa.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9 entries, 13 to 238
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   기간         9 non-null      object
 1   자치구        9 non-null      object
 2   체육도장_시설수   9 non-null      object
 3   체육단련장_시설수  9 non-null      int32
dtypes: int32(1), object(3)
memory usage: 324.0+ bytes

In [28]:
aa['체육단련장_시설수'].min(), aa['체육단련장_시설수'].max(), aa['체육단련장_시설수'].mean(), aa['체육단련장_시설수'].median()

(67, 120, 83.88888888888889, 79.0)

# groupby

# groupby_exercise

# exercise.groupby('기간')

In [57]:
exercise_year = exercise.groupby('기간')
exercise_year

In [52]:
exercise_year.sum()

      체육도장_시설수  체육단련장_시설수
기간
2010      2290       1577
2011      2373       1696
2012      2336       1735
2013      2418       1853
2014      2466       1933
2015      2384       2077
2016      2546       2192
2017      2289       2394
2018      2355       2378
2019      2198       2598

In [54]:
exercise_year.median()

      체육도장_시설수  체육단련장_시설수
기간
2010        93         62
2011        99         60
2012        92         63
2013        94         68
2014        94         70
2015        96         72
2016       105         75
2017       102         77
2018        94         74
2019        79         72

In [65]:
exercise_year.describe()

     체육도장_시설수                                                     체육단련장_시설수  \
        count    mean        std   min   25%    50%    75%    max     count
기간
2010     25.0   91.60  36.260631  17.0  71.0   93.0  107.0  160.0      25.0
2011     25.0   94.92  34.329191  21.0  74.0   99.0  126.0  151.0      25.0
2012     25.0   93.44  35.053626  19.0  79.0   92.0  109.0  161.0      25.0
2013     25.0   96.72  38.650701  22.0  77.0   94.0  113.0  180.0      25.0
2014     25.0   98.64  37.983417  26.0  77.0   94.0  120.0  169.0      25.0
2015     25.0   95.36  38.731856  25.0  75.0   96.0  113.0  159.0      25.0
2016     25.0  101.84  37.441822  27.0  83.0  105.0  119.0  161.0      25.0
2017     25.0   91.56  46.791274   8.0  62.0  102.0  115.0  163.0      25.0
2018     25.0   94.20  41.959306  24.0  61.0   94.0  118.0  164.0      25.0
2019     25.0   87.92  38.803909  22.0  61.0   79.0  113.0  173.0      25.0


        mean        std   min   25%   50%    75%    max
기간
2010   63.08  27.859648  29.0  45.0  62.0   73.0  163.0
2011   67.84  39.931900  32.0  46.0  60.0   79.0  234.0
2012   69.40  38.616706  36.0  44.0  63.0   80.0  221.0
2013   74.12  42.038990  36.0  47.0  68.0   84.0  240.0
2014   77.32  42.855105  38.0  52.0  70.0   86.0  240.0
2015   83.08  52.615682  41.0  52.0  72.0   95.0  301.0
2016   87.68  58.705991  43.0  55.0  75.0  101.0  340.0
2017   95.76  66.726606  44.0  58.0  77.0  106.0  374.0
2018   95.12  73.537020  29.0  61.0  74.0  103.0  398.0
2019  103.92  86.536563  43.0  60.0  72.0  114.0  467.0

# exercise.groupby('자치구')

In [58]:
exercise_gu = exercise.groupby('자치구')
exercise_gu

In [59]:
exercise_gu.sum()

      체육도장_시설수  체육단련장_시설수
자치구
강남구       1146       2978
강동구       1328        980
강북구        762        470
강서구       1572        972
관악구       1124        711
광진구        888        894
구로구        986        740
금천구        659        426
노원구       1465        594
도봉구        791        459
동대문구       801        753
동작구        834        584
마포구        801        853
서대문구       773        478
서초구        948       1313
성동구        839        508
성북구       1047        531
송파구       1544       1344
양천구       1332        821
영등포구      1081       1002
용산구        351        453
은평구       1099        817
종로구        212        468
중구         258        700
중랑구       1014        584

In [61]:
exercise_gu.median()

      체육도장_시설수  체육단련장_시설수
자치구
강남구      129.0      270.5
강동구      141.5       98.0
강북구       78.0       47.5
강서구      158.0       86.5
관악구      106.5       70.0
광진구       94.0       88.5
구로구       97.5       71.0
금천구       66.5       42.0
노원구      153.5       58.0
도봉구       79.0       43.0
동대문구      83.5       77.5
동작구       86.0       59.5
마포구       81.5       80.5
서대문구      75.5       48.5
서초구       96.0      127.0
성동구       84.5       46.0
성북구      107.5       53.0
송파구      148.5      139.5
양천구      130.0       85.0
영등포구     112.5       96.0
용산구       36.0       49.0
은평구      108.5       79.0
종로구       22.0       46.0
중구        26.0       71.0
중랑구      106.5       59.0

In [64]:
exercise_gu.describe()

     체육도장_시설수                                                         \
        count   mean        std    min     25%    50%     75%    max
자치구
강남구      10.0  114.6  41.671200   27.0  103.00  129.0  145.00  150.0
강동구      10.0  132.8  28.805092   55.0  129.75  141.5  146.50  155.0
강북구      10.0   76.2   9.162726   60.0   75.25   78.0   82.25   88.0
강서구      10.0  157.2   8.521867  145.0  150.25  158.0  162.50  173.0
관악구      10.0  112.4  16.581114   88.0  102.25  106.5  129.75  133.0
광진구      10.0   88.8  16.233025   50.0   94.00   94.0   97.50  100.0
구로구      10.0   98.6   6.769211   91.0   93.50   97.5  102.50  113.0
금천구      10.0   65.9   3.784471   61.0   62.75   66.5   67.00   74.0
노원구      10.0  146.5  11.257097  127.0  138.75  153.5  154.00  156.0
도봉구      10.0   79.1   2.233582   77.0   77.25   79.0   79.00   83.0
동대문구     10.0   80.1  22.975591   45.0   65.75   83.5   99.00  105.0
동작구      10.0   83.4   7.229569   71.0   78.25   86.0   87.75   93.0
마포구      10.0   80.1  24.515075   15.0   80.25   81.5   94.00  100.0
서대문구     10.0   77.3   6.600505   68.0   73.25   75.5   80.75   91.0
서초구      10.0   94.8  16.784914   71.0   80.75   96.0  106.75  118.0
성동구      10.0   83.9  16.030873   55.0   77.75   84.5   88.75  110.0
성북구      10.0  104.7   8.969702   92.0   96.25  107.5  111.50  115.0
송파구      10.0  154.4  12.988884  140.0  144.75  148.5  161.75  180.0
양천구      10.0  133.2  18.461973  104.0  121.50  130.0  150.00  160.0
영등포구     10.0  108.1  15.466451   69.0  108.25  112.5  117.75  120.0
용산구      10.0   35.1   3.784471   30.0   31.75   36.0   37.00   41.0
은평구      10.0  109.9   9.723397   98.0  104.50  108.5  112.25  134.0
종로구      10.0   21.2   5.652925    8.0   19.50   22.0   24.75   27.0
중구       10.0   25.8   1.316561   23.0   25.00   26.0   27.00   27.0
중랑구      10.0  101.4  18.963122   51.0  102.25  106.5  111.50  116.0

     체육단련장_시설수
         count   mean        std    min     25%    50%     75%    max
자치구
강남구       10.0  297.8  94.919615  163.0  235.50  270.5  365.50  467.0
강동구       10.0   98.0  11.303883   82.0   90.50   98.0  107.50  114.0
강북구       10.0   47.0   5.395471   40.0   42.00   47.5   49.00   55.0
강서구       10.0   97.2  26.951809   73.0   77.50   86.5  113.75  157.0
관악구       10.0   71.1  10.049323   57.0   64.25   70.0   76.00   90.0
광진구       10.0   89.4  10.762073   72.0   83.00   88.5   98.25  106.0
구로구       10.0   74.0  14.621141   53.0   63.75   71.0   87.75   95.0
금천구       10.0   42.6   6.113737   36.0   38.00   42.0   46.25   55.0
노원구       10.0   59.4   9.743374   46.0   53.00   58.0   68.50   73.0
도봉구       10.0   45.9   5.896327   38.0   42.25   43.0   51.25   56.0
동대문구      10.0   75.3  12.338287   60.0   63.00   77.5   83.50   92.0
동작구       10.0   58.4   7.336363   48.0   53.00   59.5   64.25   68.0
마포구       10.0   85.3  18.098803   67.0   71.00   80.5   95.50  120.0
서대문구      10.0   47.8   8.310636   37.0   40.25   48.5   52.75   61.0
서초구       10.0  131.3  43.944536   78.0   93.75  127.0  164.00  196.0
성동구       10.0   50.8  11.222992   39.0   42.25   46.0   60.50   69.0
성북구       10.0   53.1   8.075340   43.0   46.25   53.0   58.00   66.0
송파구       10.0  134.4  40.719092   46.0  117.00  139.5  158.25  191.0
양천구       10.0   82.1  23.449473   29.0   73.00   85.0  101.75  105.0
영등포구      10.0  100.2  15.647506   82.0   87.25   96.0  113.50  125.0
용산구       10.0   45.3   9.684466   29.0   38.00   49.0   52.00   57.0
은평구       10.0   81.7   8.287206   71.0   77.25   79.0   88.50   94.0
종로구       10.0   46.8   3.084009   43.0   45.00   46.0   49.50   52.0
중구        10.0   70.0   4.496913   63.0   66.50   71.0   74.00   75.0
중랑구       10.0   58.4  11.364663   47.0   49.50   59.0   59.75   86.0

# exercise.groupby(['기간','자치구'])

In [66]:
exercise_year_gu = exercise.groupby(['기간','자치구'])
exercise_year_gu

In [72]:
exercise_year_gu.sum()

           체육도장_시설수  체육단련장_시설수
기간   자치구
2010 강남구         97        163
     강동구        128         82
     강북구         83         41
     강서구        150         73
     관악구        126         62
     광진구         94         83
     구로구         93         53
     금천구         62         38
     노원구        137         46
     도봉구         83         42
     동대문구        99         62
     동작구         71         49
     마포구         94         69
     서대문구        73         37
     서초구         71         78
     성동구         77         40
     성북구         93         46
     송파구        144        104
     양천구        160         71
     영등포구        69         82
     용산구         41         29
     은평구         98         71
     종로구         17         45
     중구          23         63
     중랑구        107         48
2011 강남구        126        234
     강동구        128         82
     강북구         88         40
     강서구        151         75
     관악구        131         64
     광진구        100         86
     구로구         92         58
     금천구         74         47
     노원구        130         49
     도봉구         83         43
     동대문구        99         60
     동작구         74         48
     마포구        100         67
     서대문구        68         38
     서초구         73         84
     성동구         80         39
     성북구         92         43
     송파구        148        114
     양천구        133         79
     영등포구       108         85
     용산구         39         32
     은평구        103         71
     종로구         21         46
     중구          26         64
     중랑구        106         48
2012 강남구        121        221
     강동구        135         89
     강북구         80         41
     강서구        145         80
     관악구        133         70
     광진구         96         83
     구로구         91         63
     금천구         67         36
     노원구        144         53
     도봉구         79         41
     동대문구        95         61
     동작구         85         53
     마포구         81         79
     서대문구        74         39
     서초구         77         92
     성동구         85         42
     성북구         95         44
     송파구        161        126
     양천구        104         64
     영등포구       109         87
     용산구         37         36
     은평구        104         77
     종로구         19         45
     중구          27         66
     중랑구         92         47
2013 강남구        132        240
     강동구        145         95
     강북구         80         47
     강서구        149         77
     관악구        132         70
     광진구         94         91
     구로구         95         66
     금천구         68         36
     노원구        156         53
     도봉구         77         38
     동대문구        71         75
     동작구         88         53
     마포구         75         71
     서대문구        81         46
     서초구         92         99
     성동구         88         43
     성북구        100         47
     송파구        180        140
     양천구        113         84
     영등포구        96         88
     용산구         36         44
     은평구        109         78
     종로구         22         50
     중구          27         68
     중랑구        112         54
2014 강남구        136        240
     강동구        147         97
     강북구         76         49
     강서구        157         79
     관악구        108         57
     광진구         94         93
     구로구        101         70
     금천구         65         38
     노원구        156         53
     도봉구         77         43
     동대문구        72         82
     동작구         93         58
     마포구         80         71
     서대문구        91         44
     서초구         93        121
     성동구         89         48
     성북구        107         52
     송파구        169        150
     양천구        120         86
     영등포구       120         93
     용산구         36         49
     은평구        110         79
     종로구         27         52
     중구          26         70
     중랑구        116         59
2015 강남구        150        301
     강동구        142         99
     강북구         75         49
     강서구        159         93
     관악구         96         65
     광진구         94        100
     구로구        100         72
     금천구         67         41
     노원구        153         63
     도봉구         79         43
     동대문구       103         84
     동작구         87         62
     마포구         82         82
     서대문구        80         51
     서초구         99        133
     성동구         67         44
     성북구        108         54
     송파구        140        139
     양천구        147         95
     영등포구       113         99
     용산구         34         52
     은평구        106         79
     종로구         25         46
     중구          27         72
     중랑구         51         59
2016 강남구        148        340
     강동구        141        110
     강북구         83         55
     강서구        161        104
     관악구        105         73
     광진구         99        101
     구로구        103         84
     금천구         66         43
     노원구        154         64
     도봉구         77         49
     동대문구       105         91
     동작구         87         67
     마포구         81         88
     서대문구        83         52
     서초구        108        149
     성동구        104         56
     성북구        112         58
     송파구        147         46
     양천구        151        104
     영등포구       119        109
     용산구         37         53
     은평구        108         87
     종로구         27         48
     중구          27         75
     중랑구        113         86
2017 강남구         27        374
     강동구        152        109
     강북구         76         55
     강서구        163        117
     관악구        102         77
     광진구         98        106
     구로구        103         89
     금천구         62         44
     노원구        154         70
     도봉구         79         52
     동대문구        48         92
     동작구         90         68
     마포구         15         98
     서대문구        76         53
     서초구        103        169
     성동구        110         62
     성북구        115         58
     송파구        162        161
     양천구        151        104
     영등포구       117        115
     용산구         30         49
     은평구        113         89
     종로구          8         50
     중구          25         74
     중랑구        110         59
2018 강남구        150        398
     강동구        155        103
     강북구         60         48
     강서구        164        117
     관악구         88         83
     광진구         50         79
     구로구         95         90
     금천구         61         48
     노원구        154         73
     도봉구         78         56
     동대문구        45         80
     동작구         82         65
     마포구         94        108
     서대문구        75         61
     서초구        118        192
     성동구         84         65
     성북구        115         66
     송파구        144        173
     양천구        126         29
     영등포구       118        119
     용산구         30         52
     은평구        114         92
     종로구         24         43
     중구          25         74
     중랑구        106         64
2019 강남구         59        467
     강동구         55        114
     강북구         61         45
     강서구        173        157
     관악구        103         90
     광진구         69         72
     구로구        113         95
     금천구         67         55
     노원구        127         70
     도봉구         79         52
     동대문구        64         66
     동작구         77         61
     마포구         99        120
     서대문구        72         57
     서초구        114        196
     성동구         55         69
     성북구        110         63
     송파구        149        191
     양천구        127        105
     영등포구       112        125
     용산구         31         57
     은평구        134         94
     종로구         22         43
     중구          25         74
     중랑구        101         60

In [73]:
exercise_year_gu.median()

           체육도장_시설수  체육단련장_시설수
기간   자치구
2010 강남구         97        163
     강동구        128         82
     강북구         83         41
     강서구        150         73
     관악구        126         62
     광진구         94         83
     구로구         93         53
     금천구         62         38
     노원구        137         46
     도봉구         83         42
     동대문구        99         62
     동작구         71         49
     마포구         94         69
     서대문구        73         37
     서초구         71         78
     성동구         77         40
     성북구         93         46
     송파구        144        104
     양천구        160         71
     영등포구        69         82
     용산구         41         29
     은평구         98         71
     종로구         17         45
     중구          23         63
     중랑구        107         48
2011 강남구        126        234
     강동구        128         82
     강북구         88         40
     강서구        151         75
     관악구        131         64
     광진구        100         86
     구로구         92         58
     금천구         74         47
     노원구        130         49
     도봉구         83         43
     동대문구        99         60
     동작구         74         48
     마포구        100         67
     서대문구        68         38
     서초구         73         84
     성동구         80         39
     성북구         92         43
     송파구        148        114
     양천구        133         79
     영등포구       108         85
     용산구         39         32
     은평구        103         71
     종로구         21         46
     중구          26         64
     중랑구        106         48
2012 강남구        121        221
     강동구        135         89
     강북구         80         41
     강서구        145         80
     관악구        133         70
     광진구         96         83
     구로구         91         63
     금천구         67         36
     노원구        144         53
     도봉구         79         41
     동대문구        95         61
     동작구         85         53
     마포구         81         79
     서대문구        74         39
     서초구         77         92
     성동구         85         42
     성북구         95         44
     송파구        161        126
     양천구        104         64
     영등포구       109         87
     용산구         37         36
     은평구        104         77
     종로구         19         45
     중구          27         66
     중랑구         92         47
2013 강남구        132        240
     강동구        145         95
     강북구         80         47
     강서구        149         77
     관악구        132         70
     광진구         94         91
     구로구         95         66
     금천구         68         36
     노원구        156         53
     도봉구         77         38
     동대문구        71         75
     동작구         88         53
     마포구         75         71
     서대문구        81         46
     서초구         92         99
     성동구         88         43
     성북구        100         47
     송파구        180        140
     양천구        113         84
     영등포구        96         88
     용산구         36         44
     은평구        109         78
     종로구         22         50
     중구          27         68
     중랑구        112         54
2014 강남구        136        240
     강동구        147         97
     강북구         76         49
     강서구        157         79
     관악구        108         57
     광진구         94         93
     구로구        101         70
     금천구         65         38
     노원구        156         53
     도봉구         77         43
     동대문구        72         82
     동작구         93         58
     마포구         80         71
     서대문구        91         44
     서초구         93        121
     성동구         89         48
     성북구        107         52
     송파구        169        150
     양천구        120         86
     영등포구       120         93
     용산구         36         49
     은평구        110         79
     종로구         27         52
     중구          26         70
     중랑구        116         59
2015 강남구        150        301
     강동구        142         99
     강북구         75         49
     강서구        159         93
     관악구         96         65
     광진구         94        100
     구로구        100         72
     금천구         67         41
     노원구        153         63
     도봉구         79         43
     동대문구       103         84
     동작구         87         62
     마포구         82         82
     서대문구        80         51
     서초구         99        133
     성동구         67         44
     성북구        108         54
     송파구        140        139
     양천구        147         95
     영등포구       113         99
     용산구         34         52
     은평구        106         79
     종로구         25         46
     중구          27         72
     중랑구         51         59
2016 강남구        148        340
     강동구        141        110
     강북구         83         55
     강서구        161        104
     관악구        105         73
     광진구         99        101
     구로구        103         84
     금천구         66         43
     노원구        154         64
     도봉구         77         49
     동대문구       105         91
     동작구         87         67
     마포구         81         88
     서대문구        83         52
     서초구        108        149
     성동구        104         56
     성북구        112         58
     송파구        147         46
     양천구        151        104
     영등포구       119        109
     용산구         37         53
     은평구        108         87
     종로구         27         48
     중구          27         75
     중랑구        113         86
2017 강남구         27        374
     강동구        152        109
     강북구         76         55
     강서구        163        117
     관악구        102         77
     광진구         98        106
     구로구        103         89
     금천구         62         44
     노원구        154         70
     도봉구         79         52
     동대문구        48         92
     동작구         90         68
     마포구         15         98
     서대문구        76         53
     서초구        103        169
     성동구        110         62
     성북구        115         58
     송파구        162        161
     양천구        151        104
     영등포구       117        115
     용산구         30         49
     은평구        113         89
     종로구          8         50
     중구          25         74
     중랑구        110         59
2018 강남구        150        398
     강동구        155        103
     강북구         60         48
     강서구        164        117
     관악구         88         83
     광진구         50         79
     구로구         95         90
     금천구         61         48
     노원구        154         73
     도봉구         78         56
     동대문구        45         80
     동작구         82         65
     마포구         94        108
     서대문구        75         61
     서초구        118        192
     성동구         84         65
     성북구        115         66
     송파구        144        173
     양천구        126         29
     영등포구       118        119
     용산구         30         52
     은평구        114         92
     종로구         24         43
     중구          25         74
     중랑구        106         64
2019 강남구         59        467
     강동구         55        114
     강북구         61         45
     강서구        173        157
     관악구        103         90
     광진구         69         72
     구로구        113         95
     금천구         67         55
     노원구        127         70
     도봉구         79         52
     동대문구        64         66
     동작구         77         61
     마포구         99        120
     서대문구        72         57
     서초구        114        196
     성동구         55         69
     성북구        110         63
     송파구        149        191
     양천구        127        105
     영등포구       112        125
     용산구         31         57
     은평구        134         94
     종로구         22         43
     중구          25         74
     중랑구        101         60

In [71]:
exercise_year_gu.describe()

          체육도장_시설수                                               체육단련장_시설수  \
             count   mean std    min    25%    50%    75%    max     count
기간   자치구
2010 강남구       1.0   97.0 NaN   97.0   97.0   97.0   97.0   97.0       1.0
     강동구       1.0  128.0 NaN  128.0  128.0  128.0  128.0  128.0       1.0
     강북구       1.0   83.0 NaN   83.0   83.0   83.0   83.0   83.0       1.0
     강서구       1.0  150.0 NaN  150.0  150.0  150.0  150.0  150.0       1.0
     관악구       1.0  126.0 NaN  126.0  126.0  126.0  126.0  126.0       1.0
     광진구       1.0   94.0 NaN   94.0   94.0   94.0   94.0   94.0       1.0
     구로구       1.0   93.0 NaN   93.0   93.0   93.0   93.0   93.0       1.0
     금천구       1.0   62.0 NaN   62.0   62.0   62.0   62.0   62.0       1.0
     노원구       1.0  137.0 NaN  137.0  137.0  137.0  137.0  137.0       1.0
     도봉구       1.0   83.0 NaN   83.0   83.0   83.0   83.0   83.0       1.0
     동대문구      1.0   99.0 NaN   99.0   99.0   99.0   99.0   99.0       1.0
     동작구       1.0   71.0 NaN   71.0   71.0   71.0   71.0   71.0       1.0
     마포구       1.0   94.0 NaN   94.0   94.0   94.0   94.0   94.0       1.0
     서대문구      1.0   73.0 NaN   73.0   73.0   73.0   73.0   73.0       1.0
     서초구       1.0   71.0 NaN   71.0   71.0   71.0   71.0   71.0       1.0
     성동구       1.0   77.0 NaN   77.0   77.0   77.0   77.0   77.0       1.0
     성북구       1.0   93.0 NaN   93.0   93.0   93.0   93.0   93.0       1.0
     송파구       1.0  144.0 NaN  144.0  144.0  144.0  144.0  144.0       1.0
     양천구       1.0  160.0 NaN  160.0  160.0  160.0  160.0  160.0       1.0
     영등포구      1.0   69.0 NaN   69.0   69.0   69.0   69.0   69.0       1.0
     용산구       1.0   41.0 NaN   41.0   41.0   41.0   41.0   41.0       1.0
     은평구       1.0   98.0 NaN   98.0   98.0   98.0   98.0   98.0       1.0
     종로구       1.0   17.0 NaN   17.0   17.0   17.0   17.0   17.0       1.0
     중구        1.0   23.0 NaN   23.0   23.0   23.0   23.0   23.0       1.0
     중랑구       1.0  107.0 NaN  107.0  107.0  107.0  107.0  107.0       1.0
2011 강남구       1.0  126.0 NaN  126.0  126.0  126.0  126.0  126.0       1.0
     강동구       1.0  128.0 NaN  128.0  128.0  128.0  128.0  128.0       1.0
     강북구       1.0   88.0 NaN   88.0   88.0   88.0   88.0   88.0       1.0
     강서구       1.0  151.0 NaN  151.0  151.0  151.0  151.0  151.0       1.0
     관악구       1.0  131.0 NaN  131.0  131.0  131.0  131.0  131.0       1.0
     광진구       1.0  100.0 NaN  100.0  100.0  100.0  100.0  100.0       1.0
     구로구       1.0   92.0 NaN   92.0   92.0   92.0   92.0   92.0       1.0
     금천구       1.0   74.0 NaN   74.0   74.0   74.0   74.0   74.0       1.0
     노원구       1.0  130.0 NaN  130.0  130.0  130.0  130.0  130.0       1.0
     도봉구       1.0   83.0 NaN   83.0   83.0   83.0   83.0   83.0       1.0
     동대문구      1.0   99.0 NaN   99.0   99.0   99.0   99.0   99.0       1.0
     동작구       1.0   74.0 NaN   74.0   74.0   74.0   74.0   74.0       1.0
     마포구       1.0  100.0 NaN  100.0  100.0  100.0  100.0  100.0       1.0
     서대문구      1.0   68.0 NaN   68.0   68.0   68.0   68.0   68.0       1.0
     서초구       1.0   73.0 NaN   73.0   73.0   73.0   73.0   73.0       1.0
     성동구       1.0   80.0 NaN   80.0   80.0   80.0   80.0   80.0       1.0
     성북구       1.0   92.0 NaN   92.0   92.0   92.0   92.0   92.0       1.0
     송파구       1.0  148.0 NaN  148.0  148.0  148.0  148.0  148.0       1.0
     양천구       1.0  133.0 NaN  133.0  133.0  133.0  133.0  133.0       1.0
     영등포구      1.0  108.0 NaN  108.0  108.0  108.0  108.0  108.0       1.0
     용산구       1.0   39.0 NaN   39.0   39.0   39.0   39.0   39.0       1.0
     은평구       1.0  103.0 NaN  103.0  103.0  103.0  103.0  103.0       1.0
     종로구       1.0   21.0 NaN   21.0   21.0   21.0   21.0   21.0       1.0
     중구        1.0   26.0 NaN   26.0   26.0   26.0   26.0   26.0       1.0
     중랑구       1.0  106.0 NaN  106.0  106.0  106.0  106.0  106.0       1.0
2012 강남구       1.0  121.0 NaN  121.0  121.0  121.0  121.0  121.0       1.0
     강동구       1.0  135.0 NaN  135.0  135.0  135.0  135.0  135.0       1.0
     강북구       1.0   80.0 NaN   80.0   80.0   80.0   80.0   80.0       1.0
     강서구       1.0  145.0 NaN  145.0  145.0  145.0  145.0  145.0       1.0
     관악구       1.0  133.0 NaN  133.0  133.0  133.0  133.0  133.0       1.0
     광진구       1.0   96.0 NaN   96.0   96.0   96.0   96.0   96.0       1.0
     구로구       1.0   91.0 NaN   91.0   91.0   91.0   91.0   91.0       1.0
     금천구       1.0   67.0 NaN   67.0   67.0   67.0   67.0   67.0       1.0
     노원구       1.0  144.0 NaN  144.0  144.0  144.0  144.0  144.0       1.0
     도봉구       1.0   79.0 NaN   79.0   79.0   79.0   79.0   79.0       1.0
     동대문구      1.0   95.0 NaN   95.0   95.0   95.0   95.0   95.0       1.0
     동작구       1.0   85.0 NaN   85.0   85.0   85.0   85.0   85.0       1.0
     마포구       1.0   81.0 NaN   81.0   81.0   81.0   81.0   81.0       1.0
     서대문구      1.0   74.0 NaN   74.0   74.0   74.0   74.0   74.0       1.0
     서초구       1.0   77.0 NaN   77.0   77.0   77.0   77.0   77.0       1.0
     성동구       1.0   85.0 NaN   85.0   85.0   85.0   85.0   85.0       1.0
     성북구       1.0   95.0 NaN   95.0   95.0   95.0   95.0   95.0       1.0
     송파구       1.0  161.0 NaN  161.0  161.0  161.0  161.0  161.0       1.0
     양천구       1.0  104.0 NaN  104.0  104.0  104.0  104.0  104.0       1.0
     영등포구      1.0  109.0 NaN  109.0  109.0  109.0  109.0  109.0       1.0
     용산구       1.0   37.0 NaN   37.0   37.0   37.0   37.0   37.0       1.0
     은평구       1.0  104.0 NaN  104.0  104.0  104.0  104.0  104.0       1.0
     종로구       1.0   19.0 NaN   19.0   19.0   19.0   19.0   19.0       1.0
     중구        1.0   27.0 NaN   27.0   27.0   27.0   27.0   27.0       1.0
     중랑구       1.0   92.0 NaN   92.0   92.0   92.0   92.0   92.0       1.0
2013 강남구       1.0  132.0 NaN  132.0  132.0  132.0  132.0  132.0       1.0
     강동구       1.0  145.0 NaN  145.0  145.0  145.0  145.0  145.0       1.0
     강북구       1.0   80.0 NaN   80.0   80.0   80.0   80.0   80.0       1.0
     강서구       1.0  149.0 NaN  149.0  149.0  149.0  149.0  149.0       1.0
     관악구       1.0  132.0 NaN  132.0  132.0  132.0  132.0  132.0       1.0
     광진구       1.0   94.0 NaN   94.0   94.0   94.0   94.0   94.0       1.0
     구로구       1.0   95.0 NaN   95.0   95.0   95.0   95.0   95.0       1.0
     금천구       1.0   68.0 NaN   68.0   68.0   68.0   68.0   68.0       1.0
     노원구       1.0  156.0 NaN  156.0  156.0  156.0  156.0  156.0       1.0
     도봉구       1.0   77.0 NaN   77.0   77.0   77.0   77.0   77.0       1.0
     동대문구      1.0   71.0 NaN   71.0   71.0   71.0   71.0   71.0       1.0
     동작구       1.0   88.0 NaN   88.0   88.0   88.0   88.0   88.0       1.0
     마포구       1.0   75.0 NaN   75.0   75.0   75.0   75.0   75.0       1.0
     서대문구      1.0   81.0 NaN   81.0   81.0   81.0   81.0   81.0       1.0
     서초구       1.0   92.0 NaN   92.0   92.0   92.0   92.0   92.0       1.0
     성동구       1.0   88.0 NaN   88.0   88.0   88.0   88.0   88.0       1.0
     성북구       1.0  100.0 NaN  100.0  100.0  100.0  100.0  100.0       1.0
     송파구       1.0  180.0 NaN  180.0  180.0  180.0  180.0  180.0       1.0
     양천구       1.0  113.0 NaN  113.0  113.0  113.0  113.0  113.0       1.0
     영등포구      1.0   96.0 NaN   96.0   96.0   96.0   96.0   96.0       1.0
     용산구       1.0   36.0 NaN   36.0   36.0   36.0   36.0   36.0       1.0
     은평구       1.0  109.0 NaN  109.0  109.0  109.0  109.0  109.0       1.0
     종로구       1.0   22.0 NaN   22.0   22.0   22.0   22.0   22.0       1.0
     중구        1.0   27.0 NaN   27.0   27.0   27.0   27.0   27.0       1.0
     중랑구       1.0  112.0 NaN  112.0  112.0  112.0  112.0  112.0       1.0
2014 강남구       1.0  136.0 NaN  136.0  136.0  136.0  136.0  136.0       1.0
     강동구       1.0  147.0 NaN  147.0  147.0  147.0  147.0  147.0       1.0
     강북구       1.0   76.0 NaN   76.0   76.0   76.0   76.0   76.0       1.0
     강서구       1.0  157.0 NaN  157.0  157.0  157.0  157.0  157.0       1.0
     관악구       1.0  108.0 NaN  108.0  108.0  108.0  108.0  108.0       1.0
     광진구       1.0   94.0 NaN   94.0   94.0   94.0   94.0   94.0       1.0
     구로구       1.0  101.0 NaN  101.0  101.0  101.0  101.0  101.0       1.0
     금천구       1.0   65.0 NaN   65.0   65.0   65.0   65.0   65.0       1.0
     노원구       1.0  156.0 NaN  156.0  156.0  156.0  156.0  156.0       1.0
     도봉구       1.0   77.0 NaN   77.0   77.0   77.0   77.0   77.0       1.0
     동대문구      1.0   72.0 NaN   72.0   72.0   72.0   72.0   72.0       1.0
     동작구       1.0   93.0 NaN   93.0   93.0   93.0   93.0   93.0       1.0
     마포구       1.0   80.0 NaN   80.0   80.0   80.0   80.0   80.0       1.0
     서대문구      1.0   91.0 NaN   91.0   91.0   91.0   91.0   91.0       1.0
     서초구       1.0   93.0 NaN   93.0   93.0   93.0   93.0   93.0       1.0
     성동구       1.0   89.0 NaN   89.0   89.0   89.0   89.0   89.0       1.0
     성북구       1.0  107.0 NaN  107.0  107.0  107.0  107.0  107.0       1.0
     송파구       1.0  169.0 NaN  169.0  169.0  169.0  169.0  169.0       1.0
     양천구       1.0  120.0 NaN  120.0  120.0  120.0  120.0  120.0       1.0
     영등포구      1.0  120.0 NaN  120.0  120.0  120.0  120.0  120.0       1.0
     용산구       1.0   36.0 NaN   36.0   36.0   36.0   36.0   36.0       1.0
     은평구       1.0  110.0 NaN  110.0  110.0  110.0  110.0  110.0       1.0
     종로구       1.0   27.0 NaN   27.0   27.0   27.0   27.0   27.0       1.0
     중구        1.0   26.0 NaN   26.0   26.0   26.0   26.0   26.0       1.0
     중랑구       1.0  116.0 NaN  116.0  116.0  116.0  116.0  116.0       1.0
2015 강남구       1.0  150.0 NaN  150.0  150.0  150.0  150.0  150.0       1.0
     강동구       1.0  142.0 NaN  142.0  142.0  142.0  142.0  142.0       1.0
     강북구       1.0   75.0 NaN   75.0   75.0   75.0   75.0   75.0       1.0
     강서구       1.0  159.0 NaN  159.0  159.0  159.0  159.0  159.0       1.0
     관악구       1.0   96.0 NaN   96.0   96.0   96.0   96.0   96.0       1.0
     광진구       1.0   94.0 NaN   94.0   94.0   94.0   94.0   94.0       1.0
     구로구       1.0  100.0 NaN  100.0  100.0  100.0  100.0  100.0       1.0
     금천구       1.0   67.0 NaN   67.0   67.0   67.0   67.0   67.0       1.0
     노원구       1.0  153.0 NaN  153.0  153.0  153.0  153.0  153.0       1.0
     도봉구       1.0   79.0 NaN   79.0   79.0   79.0   79.0   79.0       1.0
     동대문구      1.0  103.0 NaN  103.0  103.0  103.0  103.0  103.0       1.0
     동작구       1.0   87.0 NaN   87.0   87.0   87.0   87.0   87.0       1.0
     마포구       1.0   82.0 NaN   82.0   82.0   82.0   82.0   82.0       1.0
     서대문구      1.0   80.0 NaN   80.0   80.0   80.0   80.0   80.0       1.0
     서초구       1.0   99.0 NaN   99.0   99.0   99.0   99.0   99.0       1.0
     성동구       1.0   67.0 NaN   67.0   67.0   67.0   67.0   67.0       1.0
     성북구       1.0  108.0 NaN  108.0  108.0  108.0  108.0  108.0       1.0
     송파구       1.0  140.0 NaN  140.0  140.0  140.0  140.0  140.0       1.0
     양천구       1.0  147.0 NaN  147.0  147.0  147.0  147.0  147.0       1.0
     영등포구      1.0  113.0 NaN  113.0  113.0  113.0  113.0  113.0       1.0
     용산구       1.0   34.0 NaN   34.0   34.0   34.0   34.0   34.0       1.0
     은평구       1.0  106.0 NaN  106.0  106.0  106.0  106.0  106.0       1.0
     종로구       1.0   25.0 NaN   25.0   25.0   25.0   25.0   25.0       1.0
     중구        1.0   27.0 NaN   27.0   27.0   27.0   27.0   27.0       1.0
     중랑구       1.0   51.0 NaN   51.0   51.0   51.0   51.0   51.0       1.0
2016 강남구       1.0  148.0 NaN  148.0  148.0  148.0  148.0  148.0       1.0
     강동구       1.0  141.0 NaN  141.0  141.0  141.0  141.0  141.0       1.0
     강북구       1.0   83.0 NaN   83.0   83.0   83.0   83.0   83.0       1.0
     강서구       1.0  161.0 NaN  161.0  161.0  161.0  161.0  161.0       1.0
     관악구       1.0  105.0 NaN  105.0  105.0  105.0  105.0  105.0       1.0
     광진구       1.0   99.0 NaN   99.0   99.0   99.0   99.0   99.0       1.0
     구로구       1.0  103.0 NaN  103.0  103.0  103.0  103.0  103.0       1.0
     금천구       1.0   66.0 NaN   66.0   66.0   66.0   66.0   66.0       1.0
     노원구       1.0  154.0 NaN  154.0  154.0  154.0  154.0  154.0       1.0
     도봉구       1.0   77.0 NaN   77.0   77.0   77.0   77.0   77.0       1.0
     동대문구      1.0  105.0 NaN  105.0  105.0  105.0  105.0  105.0       1.0
     동작구       1.0   87.0 NaN   87.0   87.0   87.0   87.0   87.0       1.0
     마포구       1.0   81.0 NaN   81.0   81.0   81.0   81.0   81.0       1.0
     서대문구      1.0   83.0 NaN   83.0   83.0   83.0   83.0   83.0       1.0
     서초구       1.0  108.0 NaN  108.0  108.0  108.0  108.0  108.0       1.0
     성동구       1.0  104.0 NaN  104.0  104.0  104.0  104.0  104.0       1.0
     성북구       1.0  112.0 NaN  112.0  112.0  112.0  112.0  112.0       1.0
     송파구       1.0  147.0 NaN  147.0  147.0  147.0  147.0  147.0       1.0
     양천구       1.0  151.0 NaN  151.0  151.0  151.0  151.0  151.0       1.0
     영등포구      1.0  119.0 NaN  119.0  119.0  119.0  119.0  119.0       1.0
     용산구       1.0   37.0 NaN   37.0   37.0   37.0   37.0   37.0       1.0
     은평구       1.0  108.0 NaN  108.0  108.0  108.0  108.0  108.0       1.0
     종로구       1.0   27.0 NaN   27.0   27.0   27.0   27.0   27.0       1.0
     중구        1.0   27.0 NaN   27.0   27.0   27.0   27.0   27.0       1.0
     중랑구       1.0  113.0 NaN  113.0  113.0  113.0  113.0  113.0       1.0
2017 강남구       1.0   27.0 NaN   27.0   27.0   27.0   27.0   27.0       1.0
     강동구       1.0  152.0 NaN  152.0  152.0  152.0  152.0  152.0       1.0
     강북구       1.0   76.0 NaN   76.0   76.0   76.0   76.0   76.0       1.0
     강서구       1.0  163.0 NaN  163.0  163.0  163.0  163.0  163.0       1.0
     관악구       1.0  102.0 NaN  102.0  102.0  102.0  102.0  102.0       1.0
     광진구       1.0   98.0 NaN   98.0   98.0   98.0   98.0   98.0       1.0
     구로구       1.0  103.0 NaN  103.0  103.0  103.0  103.0  103.0       1.0
     금천구       1.0   62.0 NaN   62.0   62.0   62.0   62.0   62.0       1.0
     노원구       1.0  154.0 NaN  154.0  154.0  154.0  154.0  154.0       1.0
     도봉구       1.0   79.0 NaN   79.0   79.0   79.0   79.0   79.0       1.0
     동대문구      1.0   48.0 NaN   48.0   48.0   48.0   48.0   48.0       1.0
     동작구       1.0   90.0 NaN   90.0   90.0   90.0   90.0   90.0       1.0
     마포구       1.0   15.0 NaN   15.0   15.0   15.0   15.0   15.0       1.0
     서대문구      1.0   76.0 NaN   76.0   76.0   76.0   76.0   76.0       1.0
     서초구       1.0  103.0 NaN  103.0  103.0  103.0  103.0  103.0       1.0
     성동구       1.0  110.0 NaN  110.0  110.0  110.0  110.0  110.0       1.0
     성북구       1.0  115.0 NaN  115.0  115.0  115.0  115.0  115.0       1.0
     송파구       1.0  162.0 NaN  162.0  162.0  162.0  162.0  162.0       1.0
     양천구       1.0  151.0 NaN  151.0  151.0  151.0  151.0  151.0       1.0
     영등포구      1.0  117.0 NaN  117.0  117.0  117.0  117.0  117.0       1.0
     용산구       1.0   30.0 NaN   30.0   30.0   30.0   30.0   30.0       1.0
     은평구       1.0  113.0 NaN  113.0  113.0  113.0  113.0  113.0       1.0
     종로구       1.0    8.0 NaN    8.0    8.0    8.0    8.0    8.0       1.0
     중구        1.0   25.0 NaN   25.0   25.0   25.0   25.0   25.0       1.0
     중랑구       1.0  110.0 NaN  110.0  110.0  110.0  110.0  110.0       1.0
2018 강남구       1.0  150.0 NaN  150.0  150.0  150.0  150.0  150.0       1.0
     강동구       1.0  155.0 NaN  155.0  155.0  155.0  155.0  155.0       1.0
     강북구       1.0   60.0 NaN   60.0   60.0   60.0   60.0   60.0       1.0
     강서구       1.0  164.0 NaN  164.0  164.0  164.0  164.0  164.0       1.0
     관악구       1.0   88.0 NaN   88.0   88.0   88.0   88.0   88.0       1.0
     광진구       1.0   50.0 NaN   50.0   50.0   50.0   50.0   50.0       1.0
     구로구       1.0   95.0 NaN   95.0   95.0   95.0   95.0   95.0       1.0
     금천구       1.0   61.0 NaN   61.0   61.0   61.0   61.0   61.0       1.0
     노원구       1.0  154.0 NaN  154.0  154.0  154.0  154.0  154.0       1.0
     도봉구       1.0   78.0 NaN   78.0   78.0   78.0   78.0   78.0       1.0
     동대문구      1.0   45.0 NaN   45.0   45.0   45.0   45.0   45.0       1.0
     동작구       1.0   82.0 NaN   82.0   82.0   82.0   82.0   82.0       1.0
     마포구       1.0   94.0 NaN   94.0   94.0   94.0   94.0   94.0       1.0
     서대문구      1.0   75.0 NaN   75.0   75.0   75.0   75.0   75.0       1.0
     서초구       1.0  118.0 NaN  118.0  118.0  118.0  118.0  118.0       1.0
     성동구       1.0   84.0 NaN   84.0   84.0   84.0   84.0   84.0       1.0
     성북구       1.0  115.0 NaN  115.0  115.0  115.0  115.0  115.0       1.0
     송파구       1.0  144.0 NaN  144.0  144.0  144.0  144.0  144.0       1.0
     양천구       1.0  126.0 NaN  126.0  126.0  126.0  126.0  126.0       1.0
     영등포구      1.0  118.0 NaN  118.0  118.0  118.0  118.0  118.0       1.0
     용산구       1.0   30.0 NaN   30.0   30.0   30.0   30.0   30.0       1.0
     은평구       1.0  114.0 NaN  114.0  114.0  114.0  114.0  114.0       1.0
     종로구       1.0   24.0 NaN   24.0   24.0   24.0   24.0   24.0       1.0
     중구        1.0   25.0 NaN   25.0   25.0   25.0   25.0   25.0       1.0
     중랑구       1.0  106.0 NaN  106.0  106.0  106.0  106.0  106.0       1.0
2019 강남구       1.0   59.0 NaN   59.0   59.0   59.0   59.0   59.0       1.0
     강동구       1.0   55.0 NaN   55.0   55.0   55.0   55.0   55.0       1.0
     강북구       1.0   61.0 NaN   61.0   61.0   61.0   61.0   61.0       1.0
     강서구       1.0  173.0 NaN  173.0  173.0  173.0  173.0  173.0       1.0
     관악구       1.0  103.0 NaN  103.0  103.0  103.0  103.0  103.0       1.0
     광진구       1.0   69.0 NaN   69.0   69.0   69.0   69.0   69.0       1.0
     구로구       1.0  113.0 NaN  113.0  113.0  113.0  113.0  113.0       1.0
     금천구       1.0   67.0 NaN   67.0   67.0   67.0   67.0   67.0       1.0
     노원구       1.0  127.0 NaN  127.0  127.0  127.0  127.0  127.0       1.0
     도봉구       1.0   79.0 NaN   79.0   79.0   79.0   79.0   79.0       1.0
     동대문구      1.0   64.0 NaN   64.0   64.0   64.0   64.0   64.0       1.0
     동작구       1.0   77.0 NaN   77.0   77.0   77.0   77.0   77.0       1.0
     마포구       1.0   99.0 NaN   99.0   99.0   99.0   99.0   99.0       1.0
     서대문구      1.0   72.0 NaN   72.0   72.0   72.0   72.0   72.0       1.0
     서초구       1.0  114.0 NaN  114.0  114.0  114.0  114.0  114.0       1.0
     성동구       1.0   55.0 NaN   55.0   55.0   55.0   55.0   55.0       1.0
     성북구       1.0  110.0 NaN  110.0  110.0  110.0  110.0  110.0       1.0
     송파구       1.0  149.0 NaN  149.0  149.0  149.0  149.0  149.0       1.0
     양천구       1.0  127.0 NaN  127.0  127.0  127.0  127.0  127.0       1.0
     영등포구      1.0  112.0 NaN  112.0  112.0  112.0  112.0  112.0       1.0
     용산구       1.0   31.0 NaN   31.0   31.0   31.0   31.0   31.0       1.0
     은평구       1.0  134.0 NaN  134.0  134.0  134.0  134.0  134.0       1.0
     종로구       1.0   22.0 NaN   22.0   22.0   22.0   22.0   22.0       1.0
     중구        1.0   25.0 NaN   25.0   25.0   25.0   25.0   25.0       1.0
     중랑구       1.0  101.0 NaN  101.0  101.0  101.0  101.0  101.0       1.0


            mean std    min    25%    50%    75%    max
기간   자치구
2010 강남구   163.0 NaN  163.0  163.0  163.0  163.0  163.0
     강동구    82.0 NaN   82.0   82.0   82.0   82.0   82.0
     강북구    41.0 NaN   41.0   41.0   41.0   41.0   41.0
     강서구    73.0 NaN   73.0   73.0   73.0   73.0   73.0
     관악구    62.0 NaN   62.0   62.0   62.0   62.0   62.0
     광진구    83.0 NaN   83.0   83.0   83.0   83.0   83.0
     구로구    53.0 NaN   53.0   53.0   53.0   53.0   53.0
     금천구    38.0 NaN   38.0   38.0   38.0   38.0   38.0
     노원구    46.0 NaN   46.0   46.0   46.0   46.0   46.0
     도봉구    42.0 NaN   42.0   42.0   42.0   42.0   42.0
     동대문구   62.0 NaN   62.0   62.0   62.0   62.0   62.0
     동작구    49.0 NaN   49.0   49.0   49.0   49.0   49.0
     마포구    69.0 NaN   69.0   69.0   69.0   69.0   69.0
     서대문구   37.0 NaN   37.0   37.0   37.0   37.0   37.0
     서초구    78.0 NaN   78.0   78.0   78.0   78.0   78.0
     성동구    40.0 NaN   40.0   40.0   40.0   40.0   40.0
     성북구    46.0 NaN   46.0   46.0   46.0   46.0   46.0
     송파구   104.0 NaN  104.0  104.0  104.0  104.0  104.0

# exercise.groupby(['자치구', '기간'])

In [74]:
exercise_gu_year = exercise.groupby(['자치구', '기간'])
exercise_gu_year

In [75]:
exercise_gu_year.sum()

           체육도장_시설수  체육단련장_시설수
자치구  기간
강남구  2010        97        163
     2011       126        234
     2012       121        221
     2013       132        240
     2014       136        240
     2015       150        301
     2016       148        340
     2017        27        374
     2018       150        398
     2019        59        467
강동구  2010       128         82
     2011       128         82
     2012       135         89
     2013       145         95
     2014       147         97
     2015       142         99
     2016       141        110
     2017       152        109
     2018       155        103
     2019        55        114
강북구  2010        83         41
     2011        88         40
     2012        80         41
     2013        80         47
     2014        76         49
     2015        75         49
     2016        83         55
     2017        76         55
     2018        60         48
     2019        61         45
강서구  2010       150         73
     2011       151         75
     2012       145         80
     2013       149         77
     2014       157         79
     2015       159         93
     2016       161        104
     2017       163        117
     2018       164        117
     2019       173        157
관악구  2010       126         62
     2011       131         64
     2012       133         70
     2013       132         70
     2014       108         57
     2015        96         65
     2016       105         73
     2017       102         77
     2018        88         83
     2019       103         90
광진구  2010        94         83
     2011       100         86
     2012        96         83
     2013        94         91
     2014        94         93
     2015        94        100
     2016        99        101
     2017        98        106
     2018        50         79
     2019        69         72
구로구  2010        93         53
     2011        92         58
     2012        91         63
     2013        95         66
     2014       101         70
     2015       100         72
     2016       103         84
     2017       103         89
     2018        95         90
     2019       113         95
금천구  2010        62         38
     2011        74         47
     2012        67         36
     2013        68         36
     2014        65         38
     2015        67         41
     2016        66         43
     2017        62         44
     2018        61         48
     2019        67         55
노원구  2010       137         46
     2011       130         49
     2012       144         53
     2013       156         53
     2014       156         53
     2015       153         63
     2016       154         64
     2017       154         70
     2018       154         73
     2019       127         70
도봉구  2010        83         42
     2011        83         43
     2012        79         41
     2013        77         38
     2014        77         43
     2015        79         43
     2016        77         49
     2017        79         52
     2018        78         56
     2019        79         52
동대문구 2010        99         62
     2011        99         60
     2012        95         61
     2013        71         75
     2014        72         82
     2015       103         84
     2016       105         91
     2017        48         92
     2018        45         80
     2019        64         66
동작구  2010        71         49
     2011        74         48
     2012        85         53
     2013        88         53
     2014        93         58
     2015        87         62
     2016        87         67
     2017        90         68
     2018        82         65
     2019        77         61
마포구  2010        94         69
     2011       100         67
     2012        81         79
     2013        75         71
     2014        80         71
     2015        82         82
     2016        81         88
     2017        15         98
     2018        94        108
     2019        99        120
서대문구 2010        73         37
     2011        68         38
     2012        74         39
     2013        81         46
     2014        91         44
     2015        80         51
     2016        83         52
     2017        76         53
     2018        75         61
     2019        72         57
서초구  2010        71         78
     2011        73         84
     2012        77         92
     2013        92         99
     2014        93        121
     2015        99        133
     2016       108        149
     2017       103        169
     2018       118        192
     2019       114        196
성동구  2010        77         40
     2011        80         39
     2012        85         42
     2013        88         43
     2014        89         48
     2015        67         44
     2016       104         56
     2017       110         62
     2018        84         65
     2019        55         69
성북구  2010        93         46
     2011        92         43
     2012        95         44
     2013       100         47
     2014       107         52
     2015       108         54
     2016       112         58
     2017       115         58
     2018       115         66
     2019       110         63
송파구  2010       144        104
     2011       148        114
     2012       161        126
     2013       180        140
     2014       169        150
     2015       140        139
     2016       147         46
     2017       162        161
     2018       144        173
     2019       149        191
양천구  2010       160         71
     2011       133         79
     2012       104         64
     2013       113         84
     2014       120         86
     2015       147         95
     2016       151        104
     2017       151        104
     2018       126         29
     2019       127        105
영등포구 2010        69         82
     2011       108         85
     2012       109         87
     2013        96         88
     2014       120         93
     2015       113         99
     2016       119        109
     2017       117        115
     2018       118        119
     2019       112        125
용산구  2010        41         29
     2011        39         32
     2012        37         36
     2013        36         44
     2014        36         49
     2015        34         52
     2016        37         53
     2017        30         49
     2018        30         52
     2019        31         57
은평구  2010        98         71
     2011       103         71
     2012       104         77
     2013       109         78
     2014       110         79
     2015       106         79
     2016       108         87
     2017       113         89
     2018       114         92
     2019       134         94
종로구  2010        17         45
     2011        21         46
     2012        19         45
     2013        22         50
     2014        27         52
     2015        25         46
     2016        27         48
     2017         8         50
     2018        24         43
     2019        22         43
중구   2010        23         63
     2011        26         64
     2012        27         66
     2013        27         68
     2014        26         70
     2015        27         72
     2016        27         75
     2017        25         74
     2018        25         74
     2019        25         74
중랑구  2010       107         48
     2011       106         48
     2012        92         47
     2013       112         54
     2014       116         59
     2015        51         59
     2016       113         86
     2017       110         59
     2018       106         64
     2019       101         60

In [76]:
exercise_gu_year.median()

           체육도장_시설수  체육단련장_시설수
자치구  기간
강남구  2010        97        163
     2011       126        234
     2012       121        221
     2013       132        240
     2014       136        240
     2015       150        301
     2016       148        340
     2017        27        374
     2018       150        398
     2019        59        467
강동구  2010       128         82
     2011       128         82
     2012       135         89
     2013       145         95
     2014       147         97
     2015       142         99
     2016       141        110
     2017       152        109
     2018       155        103
     2019        55        114
강북구  2010        83         41
     2011        88         40
     2012        80         41
     2013        80         47
     2014        76         49
     2015        75         49
     2016        83         55
     2017        76         55
     2018        60         48
     2019        61         45
강서구  2010       150         73
     2011       151         75
     2012       145         80
     2013       149         77
     2014       157         79
     2015       159         93
     2016       161        104
     2017       163        117
     2018       164        117
     2019       173        157
관악구  2010       126         62
     2011       131         64
     2012       133         70
     2013       132         70
     2014       108         57
     2015        96         65
     2016       105         73
     2017       102         77
     2018        88         83
     2019       103         90
광진구  2010        94         83
     2011       100         86
     2012        96         83
     2013        94         91
     2014        94         93
     2015        94        100
     2016        99        101
     2017        98        106
     2018        50         79
     2019        69         72
구로구  2010        93         53
     2011        92         58
     2012        91         63
     2013        95         66
     2014       101         70
     2015       100         72
     2016       103         84
     2017       103         89
     2018        95         90
     2019       113         95
금천구  2010        62         38
     2011        74         47
     2012        67         36
     2013        68         36
     2014        65         38
     2015        67         41
     2016        66         43
     2017        62         44
     2018        61         48
     2019        67         55
노원구  2010       137         46
     2011       130         49
     2012       144         53
     2013       156         53
     2014       156         53
     2015       153         63
     2016       154         64
     2017       154         70
     2018       154         73
     2019       127         70
도봉구  2010        83         42
     2011        83         43
     2012        79         41
     2013        77         38
     2014        77         43
     2015        79         43
     2016        77         49
     2017        79         52
     2018        78         56
     2019        79         52
동대문구 2010        99         62
     2011        99         60
     2012        95         61
     2013        71         75
     2014        72         82
     2015       103         84
     2016       105         91
     2017        48         92
     2018        45         80
     2019        64         66
동작구  2010        71         49
     2011        74         48
     2012        85         53
     2013        88         53
     2014        93         58
     2015        87         62
     2016        87         67
     2017        90         68
     2018        82         65
     2019        77         61
마포구  2010        94         69
     2011       100         67
     2012        81         79
     2013        75         71
     2014        80         71
     2015        82         82
     2016        81         88
     2017        15         98
     2018        94        108
     2019        99        120
서대문구 2010        73         37
     2011        68         38
     2012        74         39
     2013        81         46
     2014        91         44
     2015        80         51
     2016        83         52
     2017        76         53
     2018        75         61
     2019        72         57
서초구  2010        71         78
     2011        73         84
     2012        77         92
     2013        92         99
     2014        93        121
     2015        99        133
     2016       108        149
     2017       103        169
     2018       118        192
     2019       114        196
성동구  2010        77         40
     2011        80         39
     2012        85         42
     2013        88         43
     2014        89         48
     2015        67         44
     2016       104         56
     2017       110         62
     2018        84         65
     2019        55         69
성북구  2010        93         46
     2011        92         43
     2012        95         44
     2013       100         47
     2014       107         52
     2015       108         54
     2016       112         58
     2017       115         58
     2018       115         66
     2019       110         63
송파구  2010       144        104
     2011       148        114
     2012       161        126
     2013       180        140
     2014       169        150
     2015       140        139
     2016       147         46
     2017       162        161
     2018       144        173
     2019       149        191
양천구  2010       160         71
     2011       133         79
     2012       104         64
     2013       113         84
     2014       120         86
     2015       147         95
     2016       151        104
     2017       151        104
     2018       126         29
     2019       127        105
영등포구 2010        69         82
     2011       108         85
     2012       109         87
     2013        96         88
     2014       120         93
     2015       113         99
     2016       119        109
     2017       117        115
     2018       118        119
     2019       112        125
용산구  2010        41         29
     2011        39         32
     2012        37         36
     2013        36         44
     2014        36         49
     2015        34         52
     2016        37         53
     2017        30         49
     2018        30         52
     2019        31         57
은평구  2010        98         71
     2011       103         71
     2012       104         77
     2013       109         78
     2014       110         79
     2015       106         79
     2016       108         87
     2017       113         89
     2018       114         92
     2019       134         94
종로구  2010        17         45
     2011        21         46
     2012        19         45
     2013        22         50
     2014        27         52
     2015        25         46
     2016        27         48
     2017         8         50
     2018        24         43
     2019        22         43
중구   2010        23         63
     2011        26         64
     2012        27         66
     2013        27         68
     2014        26         70
     2015        27         72
     2016        27         75
     2017        25         74
     2018        25         74
     2019        25         74
중랑구  2010       107         48
     2011       106         48
     2012        92         47
     2013       112         54
     2014       116         59
     2015        51         59
     2016       113         86
     2017       110         59
     2018       106         64
     2019       101         60

In [77]:
exercise_gu_year.describe()

          체육도장_시설수                                               체육단련장_시설수  \
             count   mean std    min    25%    50%    75%    max     count
자치구  기간
강남구  2010      1.0   97.0 NaN   97.0   97.0   97.0   97.0   97.0       1.0
     2011      1.0  126.0 NaN  126.0  126.0  126.0  126.0  126.0       1.0
     2012      1.0  121.0 NaN  121.0  121.0  121.0  121.0  121.0       1.0
     2013      1.0  132.0 NaN  132.0  132.0  132.0  132.0  132.0       1.0
     2014      1.0  136.0 NaN  136.0  136.0  136.0  136.0  136.0       1.0
     2015      1.0  150.0 NaN  150.0  150.0  150.0  150.0  150.0       1.0
     2016      1.0  148.0 NaN  148.0  148.0  148.0  148.0  148.0       1.0
     2017      1.0   27.0 NaN   27.0   27.0   27.0   27.0   27.0       1.0
     2018      1.0  150.0 NaN  150.0  150.0  150.0  150.0  150.0       1.0
     2019      1.0   59.0 NaN   59.0   59.0   59.0   59.0   59.0       1.0
강동구  2010      1.0  128.0 NaN  128.0  128.0  128.0  128.0  128.0       1.0
     2011      1.0  128.0 NaN  128.0  128.0  128.0  128.0  128.0       1.0
     2012      1.0  135.0 NaN  135.0  135.0  135.0  135.0  135.0       1.0
     2013      1.0  145.0 NaN  145.0  145.0  145.0  145.0  145.0       1.0
     2014      1.0  147.0 NaN  147.0  147.0  147.0  147.0  147.0       1.0
     2015      1.0  142.0 NaN  142.0  142.0  142.0  142.0  142.0       1.0
     2016      1.0  141.0 NaN  141.0  141.0  141.0  141.0  141.0       1.0
     2017      1.0  152.0 NaN  152.0  152.0  152.0  152.0  152.0       1.0
     2018      1.0  155.0 NaN  155.0  155.0  155.0  155.0  155.0       1.0
     2019      1.0   55.0 NaN   55.0   55.0   55.0   55.0   55.0       1.0
강북구  2010      1.0   83.0 NaN   83.0   83.0   83.0   83.0   83.0       1.0
     2011      1.0   88.0 NaN   88.0   88.0   88.0   88.0   88.0       1.0
     2012      1.0   80.0 NaN   80.0   80.0   80.0   80.0   80.0       1.0
     2013      1.0   80.0 NaN   80.0   80.0   80.0   80.0   80.0       1.0
     2014      1.0   76.0 NaN   76.0   76.0   76.0   76.0   76.0       1.0
     2015      1.0   75.0 NaN   75.0   75.0   75.0   75.0   75.0       1.0
     2016      1.0   83.0 NaN   83.0   83.0   83.0   83.0   83.0       1.0
     2017      1.0   76.0 NaN   76.0   76.0   76.0   76.0   76.0       1.0
     2018      1.0   60.0 NaN   60.0   60.0   60.0   60.0   60.0       1.0
     2019      1.0   61.0 NaN   61.0   61.0   61.0   61.0   61.0       1.0
강서구  2010      1.0  150.0 NaN  150.0  150.0  150.0  150.0  150.0       1.0
     2011      1.0  151.0 NaN  151.0  151.0  151.0  151.0  151.0       1.0
     2012      1.0  145.0 NaN  145.0  145.0  145.0  145.0  145.0       1.0
     2013      1.0  149.0 NaN  149.0  149.0  149.0  149.0  149.0       1.0
     2014      1.0  157.0 NaN  157.0  157.0  157.0  157.0  157.0       1.0
     2015      1.0  159.0 NaN  159.0  159.0  159.0  159.0  159.0       1.0
     2016      1.0  161.0 NaN  161.0  161.0  161.0  161.0  161.0       1.0
     2017      1.0  163.0 NaN  163.0  163.0  163.0  163.0  163.0       1.0
     2018      1.0  164.0 NaN  164.0  164.0  164.0  164.0  164.0       1.0
     2019      1.0  173.0 NaN  173.0  173.0  173.0  173.0  173.0       1.0
관악구  2010      1.0  126.0 NaN  126.0  126.0  126.0  126.0  126.0       1.0
     2011      1.0  131.0 NaN  131.0  131.0  131.0  131.0  131.0       1.0
     2012      1.0  133.0 NaN  133.0  133.0  133.0  133.0  133.0       1.0
     2013      1.0  132.0 NaN  132.0  132.0  132.0  132.0  132.0       1.0
     2014      1.0  108.0 NaN  108.0  108.0  108.0  108.0  108.0       1.0
     2015      1.0   96.0 NaN   96.0   96.0   96.0   96.0   96.0       1.0
     2016      1.0  105.0 NaN  105.0  105.0  105.0  105.0  105.0       1.0
     2017      1.0  102.0 NaN  102.0  102.0  102.0  102.0  102.0       1.0
     2018      1.0   88.0 NaN   88.0   88.0   88.0   88.0   88.0       1.0
     2019      1.0  103.0 NaN  103.0  103.0  103.0  103.0  103.0       1.0
광진구  2010      1.0   94.0 NaN   94.0   94.0   94.0   94.0   94.0       1.0
     2011      1.0  100.0 NaN  100.0  100.0  100.0  100.0  100.0       1.0
     2012      1.0   96.0 NaN   96.0   96.0   96.0   96.0   96.0       1.0
     2013      1.0   94.0 NaN   94.0   94.0   94.0   94.0   94.0       1.0
     2014      1.0   94.0 NaN   94.0   94.0   94.0   94.0   94.0       1.0
     2015      1.0   94.0 NaN   94.0   94.0   94.0   94.0   94.0       1.0
     2016      1.0   99.0 NaN   99.0   99.0   99.0   99.0   99.0       1.0
     2017      1.0   98.0 NaN   98.0   98.0   98.0   98.0   98.0       1.0
     2018      1.0   50.0 NaN   50.0   50.0   50.0   50.0   50.0       1.0
     2019      1.0   69.0 NaN   69.0   69.0   69.0   69.0   69.0       1.0
구로구  2010      1.0   93.0 NaN   93.0   93.0   93.0   93.0   93.0       1.0
     2011      1.0   92.0 NaN   92.0   92.0   92.0   92.0   92.0       1.0
     2012      1.0   91.0 NaN   91.0   91.0   91.0   91.0   91.0       1.0
     2013      1.0   95.0 NaN   95.0   95.0   95.0   95.0   95.0       1.0
     2014      1.0  101.0 NaN  101.0  101.0  101.0  101.0  101.0       1.0
     2015      1.0  100.0 NaN  100.0  100.0  100.0  100.0  100.0       1.0
     2016      1.0  103.0 NaN  103.0  103.0  103.0  103.0  103.0       1.0
     2017      1.0  103.0 NaN  103.0  103.0  103.0  103.0  103.0       1.0
     2018      1.0   95.0 NaN   95.0   95.0   95.0   95.0   95.0       1.0
     2019      1.0  113.0 NaN  113.0  113.0  113.0  113.0  113.0       1.0
금천구  2010      1.0   62.0 NaN   62.0   62.0   62.0   62.0   62.0       1.0
     2011      1.0   74.0 NaN   74.0   74.0   74.0   74.0   74.0       1.0
     2012      1.0   67.0 NaN   67.0   67.0   67.0   67.0   67.0       1.0
     2013      1.0   68.0 NaN   68.0   68.0   68.0   68.0   68.0       1.0
     2014      1.0   65.0 NaN   65.0   65.0   65.0   65.0   65.0       1.0
     2015      1.0   67.0 NaN   67.0   67.0   67.0   67.0   67.0       1.0
     2016      1.0   66.0 NaN   66.0   66.0   66.0   66.0   66.0       1.0
     2017      1.0   62.0 NaN   62.0   62.0   62.0   62.0   62.0       1.0
     2018      1.0   61.0 NaN   61.0   61.0   61.0   61.0   61.0       1.0
     2019      1.0   67.0 NaN   67.0   67.0   67.0   67.0   67.0       1.0
노원구  2010      1.0  137.0 NaN  137.0  137.0  137.0  137.0  137.0       1.0
     2011      1.0  130.0 NaN  130.0  130.0  130.0  130.0  130.0       1.0
     2012      1.0  144.0 NaN  144.0  144.0  144.0  144.0  144.0       1.0
     2013      1.0  156.0 NaN  156.0  156.0  156.0  156.0  156.0       1.0
     2014      1.0  156.0 NaN  156.0  156.0  156.0  156.0  156.0       1.0
     2015      1.0  153.0 NaN  153.0  153.0  153.0  153.0  153.0       1.0
     2016      1.0  154.0 NaN  154.0  154.0  154.0  154.0  154.0       1.0
     2017      1.0  154.0 NaN  154.0  154.0  154.0  154.0  154.0       1.0
     2018      1.0  154.0 NaN  154.0  154.0  154.0  154.0  154.0       1.0
     2019      1.0  127.0 NaN  127.0  127.0  127.0  127.0  127.0       1.0
도봉구  2010      1.0   83.0 NaN   83.0   83.0   83.0   83.0   83.0       1.0
     2011      1.0   83.0 NaN   83.0   83.0   83.0   83.0   83.0       1.0
     2012      1.0   79.0 NaN   79.0   79.0   79.0   79.0   79.0       1.0
     2013      1.0   77.0 NaN   77.0   77.0   77.0   77.0   77.0       1.0
     2014      1.0   77.0 NaN   77.0   77.0   77.0   77.0   77.0       1.0
     2015      1.0   79.0 NaN   79.0   79.0   79.0   79.0   79.0       1.0
     2016      1.0   77.0 NaN   77.0   77.0   77.0   77.0   77.0       1.0
     2017      1.0   79.0 NaN   79.0   79.0   79.0   79.0   79.0       1.0
     2018      1.0   78.0 NaN   78.0   78.0   78.0   78.0   78.0       1.0
     2019      1.0   79.0 NaN   79.0   79.0   79.0   79.0   79.0       1.0
동대문구 2010      1.0   99.0 NaN   99.0   99.0   99.0   99.0   99.0       1.0
     2011      1.0   99.0 NaN   99.0   99.0   99.0   99.0   99.0       1.0
     2012      1.0   95.0 NaN   95.0   95.0   95.0   95.0   95.0       1.0
     2013      1.0   71.0 NaN   71.0   71.0   71.0   71.0   71.0       1.0
     2014      1.0   72.0 NaN   72.0   72.0   72.0   72.0   72.0       1.0
     2015      1.0  103.0 NaN  103.0  103.0  103.0  103.0  103.0       1.0
     2016      1.0  105.0 NaN  105.0  105.0  105.0  105.0  105.0       1.0
     2017      1.0   48.0 NaN   48.0   48.0   48.0   48.0   48.0       1.0
     2018      1.0   45.0 NaN   45.0   45.0   45.0   45.0   45.0       1.0
     2019      1.0   64.0 NaN   64.0   64.0   64.0   64.0   64.0       1.0
동작구  2010      1.0   71.0 NaN   71.0   71.0   71.0   71.0   71.0       1.0
     2011      1.0   74.0 NaN   74.0   74.0   74.0   74.0   74.0       1.0
     2012      1.0   85.0 NaN   85.0   85.0   85.0   85.0   85.0       1.0
     2013      1.0   88.0 NaN   88.0   88.0   88.0   88.0   88.0       1.0
     2014      1.0   93.0 NaN   93.0   93.0   93.0   93.0   93.0       1.0
     2015      1.0   87.0 NaN   87.0   87.0   87.0   87.0   87.0       1.0
     2016      1.0   87.0 NaN   87.0   87.0   87.0   87.0   87.0       1.0
     2017      1.0   90.0 NaN   90.0   90.0   90.0   90.0   90.0       1.0
     2018      1.0   82.0 NaN   82.0   82.0   82.0   82.0   82.0       1.0
     2019      1.0   77.0 NaN   77.0   77.0   77.0   77.0   77.0       1.0
마포구  2010      1.0   94.0 NaN   94.0   94.0   94.0   94.0   94.0       1.0
     2011      1.0  100.0 NaN  100.0  100.0  100.0  100.0  100.0       1.0
     2012      1.0   81.0 NaN   81.0   81.0   81.0   81.0   81.0       1.0
     2013      1.0   75.0 NaN   75.0   75.0   75.0   75.0   75.0       1.0
     2014      1.0   80.0 NaN   80.0   80.0   80.0   80.0   80.0       1.0
     2015      1.0   82.0 NaN   82.0   82.0   82.0   82.0   82.0       1.0
     2016      1.0   81.0 NaN   81.0   81.0   81.0   81.0   81.0       1.0
     2017      1.0   15.0 NaN   15.0   15.0   15.0   15.0   15.0       1.0
     2018      1.0   94.0 NaN   94.0   94.0   94.0   94.0   94.0       1.0
     2019      1.0   99.0 NaN   99.0   99.0   99.0   99.0   99.0       1.0
서대문구 2010      1.0   73.0 NaN   73.0   73.0   73.0   73.0   73.0       1.0
     2011      1.0   68.0 NaN   68.0   68.0   68.0   68.0   68.0       1.0
     2012      1.0   74.0 NaN   74.0   74.0   74.0   74.0   74.0       1.0
     2013      1.0   81.0 NaN   81.0   81.0   81.0   81.0   81.0       1.0
     2014      1.0   91.0 NaN   91.0   91.0   91.0   91.0   91.0       1.0
     2015      1.0   80.0 NaN   80.0   80.0   80.0   80.0   80.0       1.0
     2016      1.0   83.0 NaN   83.0   83.0   83.0   83.0   83.0       1.0
     2017      1.0   76.0 NaN   76.0   76.0   76.0   76.0   76.0       1.0
     2018      1.0   75.0 NaN   75.0   75.0   75.0   75.0   75.0       1.0
     2019      1.0   72.0 NaN   72.0   72.0   72.0   72.0   72.0       1.0
서초구  2010      1.0   71.0 NaN   71.0   71.0   71.0   71.0   71.0       1.0
     2011      1.0   73.0 NaN   73.0   73.0   73.0   73.0   73.0       1.0
     2012      1.0   77.0 NaN   77.0   77.0   77.0   77.0   77.0       1.0
     2013      1.0   92.0 NaN   92.0   92.0   92.0   92.0   92.0       1.0
     2014      1.0   93.0 NaN   93.0   93.0   93.0   93.0   93.0       1.0
     2015      1.0   99.0 NaN   99.0   99.0   99.0   99.0   99.0       1.0
     2016      1.0  108.0 NaN  108.0  108.0  108.0  108.0  108.0       1.0
     2017      1.0  103.0 NaN  103.0  103.0  103.0  103.0  103.0       1.0
     2018      1.0  118.0 NaN  118.0  118.0  118.0  118.0  118.0       1.0
     2019      1.0  114.0 NaN  114.0  114.0  114.0  114.0  114.0       1.0
성동구  2010      1.0   77.0 NaN   77.0   77.0   77.0   77.0   77.0       1.0
     2011      1.0   80.0 NaN   80.0   80.0   80.0   80.0   80.0       1.0
     2012      1.0   85.0 NaN   85.0   85.0   85.0   85.0   85.0       1.0
     2013      1.0   88.0 NaN   88.0   88.0   88.0   88.0   88.0       1.0
     2014      1.0   89.0 NaN   89.0   89.0   89.0   89.0   89.0       1.0
     2015      1.0   67.0 NaN   67.0   67.0   67.0   67.0   67.0       1.0
     2016      1.0  104.0 NaN  104.0  104.0  104.0  104.0  104.0       1.0
     2017      1.0  110.0 NaN  110.0  110.0  110.0  110.0  110.0       1.0
     2018      1.0   84.0 NaN   84.0   84.0   84.0   84.0   84.0       1.0
     2019      1.0   55.0 NaN   55.0   55.0   55.0   55.0   55.0       1.0
성북구  2010      1.0   93.0 NaN   93.0   93.0   93.0   93.0   93.0       1.0
     2011      1.0   92.0 NaN   92.0   92.0   92.0   92.0   92.0       1.0
     2012      1.0   95.0 NaN   95.0   95.0   95.0   95.0   95.0       1.0
     2013      1.0  100.0 NaN  100.0  100.0  100.0  100.0  100.0       1.0
     2014      1.0  107.0 NaN  107.0  107.0  107.0  107.0  107.0       1.0
     2015      1.0  108.0 NaN  108.0  108.0  108.0  108.0  108.0       1.0
     2016      1.0  112.0 NaN  112.0  112.0  112.0  112.0  112.0       1.0
     2017      1.0  115.0 NaN  115.0  115.0  115.0  115.0  115.0       1.0
     2018      1.0  115.0 NaN  115.0  115.0  115.0  115.0  115.0       1.0
     2019      1.0  110.0 NaN  110.0  110.0  110.0  110.0  110.0       1.0
송파구  2010      1.0  144.0 NaN  144.0  144.0  144.0  144.0  144.0       1.0
     2011      1.0  148.0 NaN  148.0  148.0  148.0  148.0  148.0       1.0
     2012      1.0  161.0 NaN  161.0  161.0  161.0  161.0  161.0       1.0
     2013      1.0  180.0 NaN  180.0  180.0  180.0  180.0  180.0       1.0
     2014      1.0  169.0 NaN  169.0  169.0  169.0  169.0  169.0       1.0
     2015      1.0  140.0 NaN  140.0  140.0  140.0  140.0  140.0       1.0
     2016      1.0  147.0 NaN  147.0  147.0  147.0  147.0  147.0       1.0
     2017      1.0  162.0 NaN  162.0  162.0  162.0  162.0  162.0       1.0
     2018      1.0  144.0 NaN  144.0  144.0  144.0  144.0  144.0       1.0
     2019      1.0  149.0 NaN  149.0  149.0  149.0  149.0  149.0       1.0
양천구  2010      1.0  160.0 NaN  160.0  160.0  160.0  160.0  160.0       1.0
     2011      1.0  133.0 NaN  133.0  133.0  133.0  133.0  133.0       1.0
     2012      1.0  104.0 NaN  104.0  104.0  104.0  104.0  104.0       1.0
     2013      1.0  113.0 NaN  113.0  113.0  113.0  113.0  113.0       1.0
     2014      1.0  120.0 NaN  120.0  120.0  120.0  120.0  120.0       1.0
     2015      1.0  147.0 NaN  147.0  147.0  147.0  147.0  147.0       1.0
     2016      1.0  151.0 NaN  151.0  151.0  151.0  151.0  151.0       1.0
     2017      1.0  151.0 NaN  151.0  151.0  151.0  151.0  151.0       1.0
     2018      1.0  126.0 NaN  126.0  126.0  126.0  126.0  126.0       1.0
     2019      1.0  127.0 NaN  127.0  127.0  127.0  127.0  127.0       1.0
영등포구 2010      1.0   69.0 NaN   69.0   69.0   69.0   69.0   69.0       1.0
     2011      1.0  108.0 NaN  108.0  108.0  108.0  108.0  108.0       1.0
     2012      1.0  109.0 NaN  109.0  109.0  109.0  109.0  109.0       1.0
     2013      1.0   96.0 NaN   96.0   96.0   96.0   96.0   96.0       1.0
     2014      1.0  120.0 NaN  120.0  120.0  120.0  120.0  120.0       1.0
     2015      1.0  113.0 NaN  113.0  113.0  113.0  113.0  113.0       1.0
     2016      1.0  119.0 NaN  119.0  119.0  119.0  119.0  119.0       1.0
     2017      1.0  117.0 NaN  117.0  117.0  117.0  117.0  117.0       1.0
     2018      1.0  118.0 NaN  118.0  118.0  118.0  118.0  118.0       1.0
     2019      1.0  112.0 NaN  112.0  112.0  112.0  112.0  112.0       1.0
용산구  2010      1.0   41.0 NaN   41.0   41.0   41.0   41.0   41.0       1.0
     2011      1.0   39.0 NaN   39.0   39.0   39.0   39.0   39.0       1.0
     2012      1.0   37.0 NaN   37.0   37.0   37.0   37.0   37.0       1.0
     2013      1.0   36.0 NaN   36.0   36.0   36.0   36.0   36.0       1.0
     2014      1.0   36.0 NaN   36.0   36.0   36.0   36.0   36.0       1.0
     2015      1.0   34.0 NaN   34.0   34.0   34.0   34.0   34.0       1.0
     2016      1.0   37.0 NaN   37.0   37.0   37.0   37.0   37.0       1.0
     2017      1.0   30.0 NaN   30.0   30.0   30.0   30.0   30.0       1.0
     2018      1.0   30.0 NaN   30.0   30.0   30.0   30.0   30.0       1.0
     2019      1.0   31.0 NaN   31.0   31.0   31.0   31.0   31.0       1.0
은평구  2010      1.0   98.0 NaN   98.0   98.0   98.0   98.0   98.0       1.0
     2011      1.0  103.0 NaN  103.0  103.0  103.0  103.0  103.0       1.0
     2012      1.0  104.0 NaN  104.0  104.0  104.0  104.0  104.0       1.0
     2013      1.0  109.0 NaN  109.0  109.0  109.0  109.0  109.0       1.0
     2014      1.0  110.0 NaN  110.0  110.0  110.0  110.0  110.0       1.0
     2015      1.0  106.0 NaN  106.0  106.0  106.0  106.0  106.0       1.0
     2016      1.0  108.0 NaN  108.0  108.0  108.0  108.0  108.0       1.0
     2017      1.0  113.0 NaN  113.0  113.0  113.0  113.0  113.0       1.0
     2018      1.0  114.0 NaN  114.0  114.0  114.0  114.0  114.0       1.0
     2019      1.0  134.0 NaN  134.0  134.0  134.0  134.0  134.0       1.0
종로구  2010      1.0   17.0 NaN   17.0   17.0   17.0   17.0   17.0       1.0
     2011      1.0   21.0 NaN   21.0   21.0   21.0   21.0   21.0       1.0
     2012      1.0   19.0 NaN   19.0   19.0   19.0   19.0   19.0       1.0
     2013      1.0   22.0 NaN   22.0   22.0   22.0   22.0   22.0       1.0
     2014      1.0   27.0 NaN   27.0   27.0   27.0   27.0   27.0       1.0
     2015      1.0   25.0 NaN   25.0   25.0   25.0   25.0   25.0       1.0
     2016      1.0   27.0 NaN   27.0   27.0   27.0   27.0   27.0       1.0
     2017      1.0    8.0 NaN    8.0    8.0    8.0    8.0    8.0       1.0
     2018      1.0   24.0 NaN   24.0   24.0   24.0   24.0   24.0       1.0
     2019      1.0   22.0 NaN   22.0   22.0   22.0   22.0   22.0       1.0
중구   2010      1.0   23.0 NaN   23.0   23.0   23.0   23.0   23.0       1.0
     2011      1.0   26.0 NaN   26.0   26.0   26.0   26.0   26.0       1.0
     2012      1.0   27.0 NaN   27.0   27.0   27.0   27.0   27.0       1.0
     2013      1.0   27.0 NaN   27.0   27.0   27.0   27.0   27.0       1.0
     2014      1.0   26.0 NaN   26.0   26.0   26.0   26.0   26.0       1.0
     2015      1.0   27.0 NaN   27.0   27.0   27.0   27.0   27.0       1.0
     2016      1.0   27.0 NaN   27.0   27.0   27.0   27.0   27.0       1.0
     2017      1.0   25.0 NaN   25.0   25.0   25.0   25.0   25.0       1.0
     2018      1.0   25.0 NaN   25.0   25.0   25.0   25.0   25.0       1.0
     2019      1.0   25.0 NaN   25.0   25.0   25.0   25.0   25.0       1.0
중랑구  2010      1.0  107.0 NaN  107.0  107.0  107.0  107.0  107.0       1.0
     2011      1.0  106.0 NaN  106.0  106.0  106.0  106.0  106.0       1.0
     2012      1.0   92.0 NaN   92.0   92.0   92.0   92.0   92.0       1.0
     2013      1.0  112.0 NaN  112.0  112.0  112.0  112.0  112.0       1.0
     2014      1.0  116.0 NaN  116.0  116.0  116.0  116.0  116.0       1.0
     2015      1.0   51.0 NaN   51.0   51.0   51.0   51.0   51.0       1.0
     2016      1.0  113.0 NaN  113.0  113.0  113.0  113.0  113.0       1.0
     2017      1.0  110.0 NaN  110.0  110.0  110.0  110.0  110.0       1.0
     2018      1.0  106.0 NaN  106.0  106.0  106.0  106.0  106.0       1.0
     2019      1.0  101.0 NaN  101.0  101.0  101.0  101.0  101.0       1.0


            mean std    min    25%    50%    75%    max
자치구  기간
강남구  2010  163.0 NaN  163.0  163.0  163.0  163.0  163.0
     2011  234.0 NaN  234.0  234.0  234.0  234.0  234.0
     2012  221.0 NaN  221.0  221.0  221.0  221.0  221.0
     2013  240.0 NaN  240.0  240.0  240.0  240.0  240.0
     2014  240.0 NaN  240.0  240.0  240.0  240.0  240.0
     2015  301.0 NaN  301.0  301.0  301.0  301.0  301.0
     2016  340.0 NaN  340.0  340.0  340.0  340.0  340.0
     2017  374.0 NaN  374.0  374.0  374.0  374.0  374.0
     2018  398.0 NaN  398.0  398.0  398.0  398.0  398.0
     2019  467.0 NaN  467.0  467.0  467.0  467.0  467.0
강동구  2010   82.0 NaN   82.0   82.0   82.0   82.0   82.0
     2011   82.0 NaN   82.0   82.0   82.0   82.0   82.0
     2012   89.0 NaN   89.0   89.0   89.0   89.0   89.0
     2013   95.0 NaN   95.0   95.0   95.0   95.0   95.0
     2014   97.0 NaN   97.0   97.0   97.0   97.0   97.0
     2015   99.0 NaN   99.0   99.0   99.0   99.0   99.0
     2016  110.0 NaN  110.0  110.0  110.0  110.0  110.0
     2017  109.0 NaN  109.0  109.0  109.0  109.0  109.0

# plot

# concat_Only recent year

In [11]:
edu_library

# 
# 2012 ~ 2018년에서 2018년만.

       기간  자치구 평생학습관 도서관
0    2012  종로구     3   1
1    2012   중구     1   1
2    2012  용산구     2   2
3    2012  성동구     1   4
4    2012  광진구     2   4
..    ...  ...   ...  ..
170  2018  관악구     3   4
171  2018  서초구     3   4
172  2018  강남구     5  10
173  2018  송파구     2  12
174  2018  강동구     3   7

[175 rows x 4 columns]

In [10]:
exercise

# 2017년 마포구의 체육단련장_시설수, ('-')로 되어있었음.
# 16년 88개, 18년 108개여서 중간 값으로 채웠음.
# exercise['체육단련장_시설수'] = exercise['체육단련장_시설수'].replace('-', '98')

# 2010 ~ 2019년에서 2019년만.

       기간  자치구 체육도장_시설수 체육단련장_시설수
0    2010  종로구       17        45
1    2010   중구       23        63
2    2010  용산구       41        29
3    2010  성동구       77        40
4    2010  광진구       94        83
..    ...  ...      ...       ...
245  2019  관악구      103        90
246  2019  서초구      114       196
247  2019  강남구       59       467
248  2019  송파구      149       191
249  2019  강동구       55       114

[250 rows x 4 columns]

In [18]:
edu_library[edu_library['기간']=='2018']

       기간   자치구 평생학습관 도서관
150  2018   종로구     3   3
151  2018    중구     1   2
152  2018   용산구     3   1
153  2018   성동구     3   4
154  2018   광진구     2   4
155  2018  동대문구     2   3
156  2018   중랑구     3   3
157  2018   성북구     2  10
158  2018   강북구     2   7
159  2018   도봉구     4   5
160  2018   노원구     3   5
161  2018   은평구     3   5
162  2018  서대문구     3   1
163  2018   마포구     3   3
164  2018   양천구     3   5
165  2018   강서구     3  10
166  2018   구로구     4   9
167  2018   금천구     3   -
168  2018  영등포구     4   5
169  2018   동작구     3   4
170  2018   관악구     3   4
171  2018   서초구     3   4
172  2018   강남구     5  10
173  2018   송파구     2  12
174  2018   강동구     3   7

In [19]:
exercise[exercise['기간']=='2019']

       기간   자치구 체육도장_시설수 체육단련장_시설수
225  2019   종로구       22        43
226  2019    중구       25        74
227  2019   용산구       31        57
228  2019   성동구       55        69
229  2019   광진구       69        72
230  2019  동대문구       64        66
231  2019   중랑구      101        60
232  2019   성북구      110        63
233  2019   강북구       61        45
234  2019   도봉구       79        52
235  2019   노원구      127        70
236  2019   은평구      134        94
237  2019  서대문구       72        57
238  2019   마포구       99       120
239  2019   양천구      127       105
240  2019   강서구      173       157
241  2019   구로구      113        95
242  2019   금천구       67        55
243  2019  영등포구      112       125
244  2019   동작구       77        61
245  2019   관악구      103        90
246  2019   서초구      114       196
247  2019   강남구       59       467
248  2019   송파구      149       191
249  2019   강동구       55       114

In [31]:
a = edu_library[edu_library['기간']=='2018']
a

       기간   자치구 평생학습관 도서관
150  2018   종로구     3   3
151  2018    중구     1   2
152  2018   용산구     3   1
153  2018   성동구     3   4
154  2018   광진구     2   4
155  2018  동대문구     2   3
156  2018   중랑구     3   3
157  2018   성북구     2  10
158  2018   강북구     2   7
159  2018   도봉구     4   5
160  2018   노원구     3   5
161  2018   은평구     3   5
162  2018  서대문구     3   1
163  2018   마포구     3   3
164  2018   양천구     3   5
165  2018   강서구     3  10
166  2018   구로구     4   9
167  2018   금천구     3   -
168  2018  영등포구     4   5
169  2018   동작구     3   4
170  2018   관악구     3   4
171  2018   서초구     3   4
172  2018   강남구     5  10
173  2018   송파구     2  12
174  2018   강동구     3   7

In [32]:
b = exercise[exercise['기간']=='2019']
b

       기간   자치구 체육도장_시설수 체육단련장_시설수
225  2019   종로구       22        43
226  2019    중구       25        74
227  2019   용산구       31        57
228  2019   성동구       55        69
229  2019   광진구       69        72
230  2019  동대문구       64        66
231  2019   중랑구      101        60
232  2019   성북구      110        63
233  2019   강북구       61        45
234  2019   도봉구       79        52
235  2019   노원구      127        70
236  2019   은평구      134        94
237  2019  서대문구       72        57
238  2019   마포구       99       120
239  2019   양천구      127       105
240  2019   강서구      173       157
241  2019   구로구      113        95
242  2019   금천구       67        55
243  2019  영등포구      112       125
244  2019   동작구       77        61
245  2019   관악구      103        90
246  2019   서초구      114       196
247  2019   강남구       59       467
248  2019   송파구      149       191
249  2019   강동구       55       114

In [25]:
edu = pd.concat([a, b],
                axis=1,
                ignore_index=True,
                sort='자치구')
edu

# ignore_index=True를 넣으면 reset_index(drop=True)와 같음.
# ignore_index=False(default)는 concat하기 전, 원래의 index를 그대로 가져감.
# 이 옵션을 넣어주지 않으면 index를 다시 정리해줘야 함.


## 컬럼이 옆으로 안붙는 이유는.. dtypes가 object로 되어있어서 그런 것 같음.
## 도서관 수, nan, '-'가 있음.

        0    1    2    3    4
150   종로구    3    3  NaN  NaN
151    중구    1    2  NaN  NaN
152   용산구    3    1  NaN  NaN
153   성동구    3    4  NaN  NaN
154   광진구    2    4  NaN  NaN
155  동대문구    2    3  NaN  NaN
156   중랑구    3    3  NaN  NaN
157   성북구    2   10  NaN  NaN
158   강북구    2    7  NaN  NaN
159   도봉구    4    5  NaN  NaN
160   노원구    3    5  NaN  NaN
161   은평구    3    5  NaN  NaN
162  서대문구    3    1  NaN  NaN
163   마포구    3    3  NaN  NaN
164   양천구    3    5  NaN  NaN
165   강서구    3   10  NaN  NaN
166   구로구    4    9  NaN  NaN
167   금천구    3    -  NaN  NaN
168  영등포구    4    5  NaN  NaN
169   동작구    3    4  NaN  NaN
170   관악구    3    4  NaN  NaN
171   서초구    3    4  NaN  NaN
172   강남구    5   10  NaN  NaN
173   송파구    2   12  NaN  NaN
174   강동구    3    7  NaN  NaN
225   NaN  NaN  NaN   22   43
226   NaN  NaN  NaN   25   74
227   NaN  NaN  NaN   31   57
228   NaN  NaN  NaN   55   69
229   NaN  NaN  NaN   69   72
230   NaN  NaN  NaN   64   66
231   NaN  NaN  NaN  101   60
232   NaN  NaN  NaN  110   63
233   NaN  NaN  NaN   61   45
234   NaN  NaN  NaN   79   52
235   NaN  NaN  NaN  127   70
236   NaN  NaN  NaN  134   94
237   NaN  NaN  NaN   72   57
238   NaN  NaN  NaN   99  120
239   NaN  NaN  NaN  127  105
240   NaN  NaN  NaN  173  157
241   NaN  NaN  NaN  113   95
242   NaN  NaN  NaN   67   55
243   NaN  NaN  NaN  112  125
244   NaN  NaN  NaN   77   61
245   NaN  NaN  NaN  103   90
246   NaN  NaN  NaN  114  196
247   NaN  NaN  NaN   59  467
248   NaN  NaN  NaN  149  191
249   NaN  NaN  NaN   55  114

In [34]:
pd.concat([a,b], axis=1)

       기간   자치구 평생학습관  도서관    기간   자치구 체육도장_시설수 체육단련장_시설수
150  2018   종로구     3    3   NaN   NaN      NaN       NaN
151  2018    중구     1    2   NaN   NaN      NaN       NaN
152  2018   용산구     3    1   NaN   NaN      NaN       NaN
153  2018   성동구     3    4   NaN   NaN      NaN       NaN
154  2018   광진구     2    4   NaN   NaN      NaN       NaN
155  2018  동대문구     2    3   NaN   NaN      NaN       NaN
156  2018   중랑구     3    3   NaN   NaN      NaN       NaN
157  2018   성북구     2   10   NaN   NaN      NaN       NaN
158  2018   강북구     2    7   NaN   NaN      NaN       NaN
159  2018   도봉구     4    5   NaN   NaN      NaN       NaN
160  2018   노원구     3    5   NaN   NaN      NaN       NaN
161  2018   은평구     3    5   NaN   NaN      NaN       NaN
162  2018  서대문구     3    1   NaN   NaN      NaN       NaN
163  2018   마포구     3    3   NaN   NaN      NaN       NaN
164  2018   양천구     3    5   NaN   NaN      NaN       NaN
165  2018   강서구     3   10   NaN   NaN      NaN       NaN
166  2018   구로구     4    9   NaN   NaN      NaN       NaN
167  2018   금천구     3    -   NaN   NaN      NaN       NaN
168  2018  영등포구     4    5   NaN   NaN      NaN       NaN
169  2018   동작구     3    4   NaN   NaN      NaN       NaN
170  2018   관악구     3    4   NaN   NaN      NaN       NaN
171  2018   서초구     3    4   NaN   NaN      NaN       NaN
172  2018   강남구     5   10   NaN   NaN      NaN       NaN
173  2018   송파구     2   12   NaN   NaN      NaN       NaN
174  2018   강동구     3    7   NaN   NaN      NaN       NaN
225   NaN   NaN   NaN  NaN  2019   종로구       22        43
226   NaN   NaN   NaN  NaN  2019    중구       25        74
227   NaN   NaN   NaN  NaN  2019   용산구       31        57
228   NaN   NaN   NaN  NaN  2019   성동구       55        69
229   NaN   NaN   NaN  NaN  2019   광진구       69        72
230   NaN   NaN   NaN  NaN  2019  동대문구       64        66
231   NaN   NaN   NaN  NaN  2019   중랑구      101        60
232   NaN   NaN   NaN  NaN  2019   성북구      110        63
233   NaN   NaN   NaN  NaN  2019   강북구       61        45
234   NaN   NaN   NaN  NaN  2019   도봉구       79        52
235   NaN   NaN   NaN  NaN  2019   노원구      127        70
236   NaN   NaN   NaN  NaN  2019   은평구      134        94
237   NaN   NaN   NaN  NaN  2019  서대문구       72        57
238   NaN   NaN   NaN  NaN  2019   마포구       99       120
239   NaN   NaN   NaN  NaN  2019   양천구      127       105
240   NaN   NaN   NaN  NaN  2019   강서구      173       157
241   NaN   NaN   NaN  NaN  2019   구로구      113        95
242   NaN   NaN   NaN  NaN  2019   금천구       67        55
243   NaN   NaN   NaN  NaN  2019  영등포구      112       125
244   NaN   NaN   NaN  NaN  2019   동작구       77        61
245   NaN   NaN   NaN  NaN  2019   관악구      103        90
246   NaN   NaN   NaN  NaN  2019   서초구      114       196
247   NaN   NaN   NaN  NaN  2019   강남구       59       467
248   NaN   NaN   NaN  NaN  2019   송파구      149       191
249   NaN   NaN   NaN  NaN  2019   강동구       55       114

In [35]:
a.dtypes

기간       object
자치구      object
평생학습관    object
도서관      object
dtype: object

In [36]:
b.dtypes

기간           object
자치구          object
체육도장_시설수     object
체육단련장_시설수    object
dtype: object

In [37]:
pd.concat([edu_library.iloc[:5,:], exercise.iloc[:5,:]], axis=1)

     기간  자치구 평생학습관 도서관    기간  자치구 체육도장_시설수 체육단련장_시설수
0  2012  종로구     3   1  2010  종로구       17        45
1  2012   중구     1   1  2010   중구       23        63
2  2012  용산구     2   2  2010  용산구       41        29
3  2012  성동구     1   4  2010  성동구       77        40
4  2012  광진구     2   4  2010  광진구       94        83

In [38]:
a

# 도서관 수에 대한 데이터를 신뢰할 수 없어서 (년도별로 증감하는 모습이 상식적으로 말이 되지 않았고 도서관의 종류도 어떤 것을 수집했는지에 대한 의문점이 있음.)
# 'https://lib.seoul.go.kr/slibsrch/main'에서 자치구별로 2021년 현재 기준에서 데이터를 직접 수집함.
# 도서관 구분(종류): 대표, 국립, 공공, 작은, 장애인, 전문 도서관.
# 6가지 도서관 종류 중 대표, 국립, 공공도서관의 수만 집계함.
# 작은 도서관은 아파트 주민 전용 도서관, 회사 도서관 등도 포함되어 있기 때문에 제외함.
# 장애인, 전문 도서관도 일반인이 접근하기 어려운 도서관임.

       기간   자치구 평생학습관 도서관
150  2018   종로구     3   3
151  2018    중구     1   2
152  2018   용산구     3   1
153  2018   성동구     3   4
154  2018   광진구     2   4
155  2018  동대문구     2   3
156  2018   중랑구     3   3
157  2018   성북구     2  10
158  2018   강북구     2   7
159  2018   도봉구     4   5
160  2018   노원구     3   5
161  2018   은평구     3   5
162  2018  서대문구     3   1
163  2018   마포구     3   3
164  2018   양천구     3   5
165  2018   강서구     3  10
166  2018   구로구     4   9
167  2018   금천구     3   -
168  2018  영등포구     4   5
169  2018   동작구     3   4
170  2018   관악구     3   4
171  2018   서초구     3   4
172  2018   강남구     5  10
173  2018   송파구     2  12
174  2018   강동구     3   7

In [46]:
# a에서 평생학습관 수만 사용하고 도서관 수는 새로 수집한 것으로..

a_1 = a[['자치구', '평생학습관']].astype({'평생학습관':int})
a_1

# 평생학습관의 수: 최신 년도는 2018년도.

      자치구  평생학습관
150   종로구      3
151    중구      1
152   용산구      3
153   성동구      3
154   광진구      2
155  동대문구      2
156   중랑구      3
157   성북구      2
158   강북구      2
159   도봉구      4
160   노원구      3
161   은평구      3
162  서대문구      3
163   마포구      3
164   양천구      3
165   강서구      3
166   구로구      4
167   금천구      3
168  영등포구      4
169   동작구      3
170   관악구      3
171   서초구      3
172   강남구      5
173   송파구      2
174   강동구      3

In [44]:
# 도서관의 수(대표, 국립, 공공도서관)
# 대표 도서관: 중구
# 국립 도서관: 강남구, 서초구, 영등포구
# 공공 도서관: 이외

a_2 = pd.DataFrame({"자치구":['강남구','강동구','강북구','강서구','관악구','광진구','구로구','금천구','노원구','도봉구',
                           '동대문구','동작구','마포구','서대문구','서초구','성동구','성북구','송파구','양천구','영등포구',
                           '용산구','은평구','종로구','중구','중랑구'],
                    "도서관":[14,9,7,9,5,5,12,4,11,6,7,5,7,4,9,7,13,12,9,6,4,8,7,6,5]})
a_2

# 도서관의 수: 최신 년도는 2021년도.

     자치구  도서관
0    강남구   14
1    강동구    9
2    강북구    7
3    강서구    9
4    관악구    5
5    광진구    5
6    구로구   12
7    금천구    4
8    노원구   11
9    도봉구    6
10  동대문구    7
11   동작구    5
12   마포구    7
13  서대문구    4
14   서초구    9
15   성동구    7
16   성북구   13
17   송파구   12
18   양천구    9
19  영등포구    6
20   용산구    4
21   은평구    8
22   종로구    7
23    중구    6
24   중랑구    5

In [45]:
a_2.dtypes

자치구    object
도서관     int64
dtype: object

In [56]:
b = b[['자치구', '체육도장_시설수', '체육단련장_시설수']]
b

# 체육도장_시설수 : 최신 년도는 2019년도.
# 체육단련장_시설수 : 최신 년도는 2019년도.

      자치구  체육도장_시설수  체육단련장_시설수
225   종로구        22         43
226    중구        25         74
227   용산구        31         57
228   성동구        55         69
229   광진구        69         72
230  동대문구        64         66
231   중랑구       101         60
232   성북구       110         63
233   강북구        61         45
234   도봉구        79         52
235   노원구       127         70
236   은평구       134         94
237  서대문구        72         57
238   마포구        99        120
239   양천구       127        105
240   강서구       173        157
241   구로구       113         95
242   금천구        67         55
243  영등포구       112        125
244   동작구        77         61
245   관악구       103         90
246   서초구       114        196
247   강남구        59        467
248   송파구       149        191
249   강동구        55        114

In [47]:
b.dtypes

기간           object
자치구          object
체육도장_시설수     object
체육단련장_시설수    object
dtype: object

In [49]:
b = b.astype({'체육도장_시설수':int, '체육단련장_시설수':int})

In [58]:
# a와 b 모두 데이터타입 바꿔줌으로 concat 가능.

c = pd.concat([a_1,a_2,b], axis=1)
c

# nan 왜 생기는지..
# index 번호가 일치하지 않아서?

     자치구  평생학습관  자치구   도서관  자치구  체육도장_시설수  체육단련장_시설수
0    NaN    NaN  강남구  14.0  NaN       NaN        NaN
1    NaN    NaN  강동구   9.0  NaN       NaN        NaN
2    NaN    NaN  강북구   7.0  NaN       NaN        NaN
3    NaN    NaN  강서구   9.0  NaN       NaN        NaN
4    NaN    NaN  관악구   5.0  NaN       NaN        NaN
..   ...    ...  ...   ...  ...       ...        ...
245  NaN    NaN  NaN   NaN  관악구     103.0       90.0
246  NaN    NaN  NaN   NaN  서초구     114.0      196.0
247  NaN    NaN  NaN   NaN  강남구      59.0      467.0
248  NaN    NaN  NaN   NaN  송파구     149.0      191.0
249  NaN    NaN  NaN   NaN  강동구      55.0      114.0

[75 rows x 7 columns]

In [69]:
# nan이 생기면서 컬럼이 제대로 바로 옆에 안붙는 현상은 해결함.
# 그러나 a_1, a_2, b의 컬럼 '자치구' 값의 순서가 다르므로 그냥 concat을 할 경우, 데이터의 배열 순서가 맞지 않는 모습.

a_1 = a_1.reset_index(drop=True)
a_2 = a_2.reset_index(drop=True)
b = b.reset_index(drop=True)

c = pd.concat([a_1,a_2,b], axis=1)
c

# df = pd.concat(ignore_index=True)
# concat의 파라미터

# df.reset_index(drop=True)
# function임.

# 둘다 같은 효과.

     자치구  평생학습관   자치구  도서관   자치구  체육도장_시설수  체육단련장_시설수
0    종로구      3   강남구   14   종로구        22         43
1     중구      1   강동구    9    중구        25         74
2    용산구      3   강북구    7   용산구        31         57
3    성동구      3   강서구    9   성동구        55         69
4    광진구      2   관악구    5   광진구        69         72
5   동대문구      2   광진구    5  동대문구        64         66
6    중랑구      3   구로구   12   중랑구       101         60
7    성북구      2   금천구    4   성북구       110         63
8    강북구      2   노원구   11   강북구        61         45
9    도봉구      4   도봉구    6   도봉구        79         52
10   노원구      3  동대문구    7   노원구       127         70
11   은평구      3   동작구    5   은평구       134         94
12  서대문구      3   마포구    7  서대문구        72         57
13   마포구      3  서대문구    4   마포구        99        120
14   양천구      3   서초구    9   양천구       127        105
15   강서구      3   성동구    7   강서구       173        157
16   구로구      4   성북구   13   구로구       113         95
17   금천구      3   송파구   12   금천구        67         55
18  영등포구      4   양천구    9  영등포구       112        125
19   동작구      3  영등포구    6   동작구        77         61
20   관악구      3   용산구    4   관악구       103         90
21   서초구      3   은평구    8   서초구       114        196
22   강남구      5   종로구    7   강남구        59        467
23   송파구      2    중구    6   송파구       149        191
24   강동구      3   중랑구    5   강동구        55        114

In [71]:
# merge는 2개씩만 가능.
# on = '' / primary key(pk)와 같이 id라는 컬럼을 공통으로 가지고 있는 데이터라면 id라는 키로 매칭하여 데이터를 붙이는 것.
# how = '' / join 방식 : inner(left or right) - 교집합, outer - 합집합

a = pd.merge(a_1, a_2, on='자치구', how='inner')  # left join
a

     자치구  평생학습관  도서관
0    종로구      3    7
1     중구      1    6
2    용산구      3    4
3    성동구      3    7
4    광진구      2    5
5   동대문구      2    7
6    중랑구      3    5
7    성북구      2   13
8    강북구      2    7
9    도봉구      4    6
10   노원구      3   11
11   은평구      3    8
12  서대문구      3    4
13   마포구      3    7
14   양천구      3    9
15   강서구      3    9
16   구로구      4   12
17   금천구      3    4
18  영등포구      4    6
19   동작구      3    5
20   관악구      3    5
21   서초구      3    9
22   강남구      5   14
23   송파구      2   12
24   강동구      3    9

In [72]:
c = pd.merge(a, b, on='자치구', how='inner')
c

     자치구  평생학습관  도서관  체육도장_시설수  체육단련장_시설수
0    종로구      3    7        22         43
1     중구      1    6        25         74
2    용산구      3    4        31         57
3    성동구      3    7        55         69
4    광진구      2    5        69         72
5   동대문구      2    7        64         66
6    중랑구      3    5       101         60
7    성북구      2   13       110         63
8    강북구      2    7        61         45
9    도봉구      4    6        79         52
10   노원구      3   11       127         70
11   은평구      3    8       134         94
12  서대문구      3    4        72         57
13   마포구      3    7        99        120
14   양천구      3    9       127        105
15   강서구      3    9       173        157
16   구로구      4   12       113         95
17   금천구      3    4        67         55
18  영등포구      4    6       112        125
19   동작구      3    5        77         61
20   관악구      3    5       103         90
21   서초구      3    9       114        196
22   강남구      5   14        59        467
23   송파구      2   12       149        191
24   강동구      3    9        55        114

In [74]:
c.dtypes

자치구          object
평생학습관         int32
도서관           int64
체육도장_시설수      int32
체육단련장_시설수     int32
dtype: object

In [80]:
c = c.rename(columns={'체육도장_시설수':'체육도장', '체육단련장_시설수':'체육단련장'})

c.to_csv('dataset_edu.csv')
c

# 컬럼 이름/단위 : 평생학습관(갯수), 도서관(갯수), 체육도장(갯수), 체육단련장(갯수)
# 데이터 기간(각 컬럼별 최신 데이터 기준) : 평생학습관(2018), 도서관(2021), 체육도장(2019), 체육단련장(2019)
# 도서관의 수(대표 + 국립 + 공공도서관)
# 대표 도서관: 중구
# 국립 도서관: 강남구, 서초구, 영등포구
# 공공 도서관: 이외

     자치구  평생학습관  도서관  체육도장  체육단련장
0    종로구      3    7    22     43
1     중구      1    6    25     74
2    용산구      3    4    31     57
3    성동구      3    7    55     69
4    광진구      2    5    69     72
5   동대문구      2    7    64     66
6    중랑구      3    5   101     60
7    성북구      2   13   110     63
8    강북구      2    7    61     45
9    도봉구      4    6    79     52
10   노원구      3   11   127     70
11   은평구      3    8   134     94
12  서대문구      3    4    72     57
13   마포구      3    7    99    120
14   양천구      3    9   127    105
15   강서구      3    9   173    157
16   구로구      4   12   113     95
17   금천구      3    4    67     55
18  영등포구      4    6   112    125
19   동작구      3    5    77     61
20   관악구      3    5   103     90
21   서초구      3    9   114    196
22   강남구      5   14    59    467
23   송파구      2   12   149    191
24   강동구      3    9    55    114